import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export type NginxUnlimitedPolicyRow = {
  keyValue: string
  enabled: boolean
  totalConcurrency: number
}

export type NginxUnlimitedPolicy = {
  version: 1
  unlimitedKeys: string[]
}

export type NginxUnlimitedPolicyRequest = NginxUnlimitedPolicy & {
  requestId: string
  policyHash: string
}

const API_KEY_PATTERN = /^sk-[A-Za-z0-9._-]{8,252}$/
const MAX_UNLIMITED_KEYS = 1_000

function normalizeKeys(values: unknown[]): string[] {
  if (values.length > MAX_UNLIMITED_KEYS) throw new Error(`不限速 API Key 不能超过 ${MAX_UNLIMITED_KEYS} 个`)
  const keys = values.map((value) => {
    if (typeof value !== 'string' || !API_KEY_PATTERN.test(value)) {
      throw new Error('不限速策略包含非法 API Key')
    }
    return value
  })
  return [...new Set(keys)].sort()
}

export function buildNginxUnlimitedPolicy(rows: NginxUnlimitedPolicyRow[]): NginxUnlimitedPolicy {
  return {
    version: 1,
    unlimitedKeys: normalizeKeys(rows
      .filter((row) => row.enabled && row.totalConcurrency === 0)
      .map((row) => row.keyValue)),
  }
}

export function parseNginxUnlimitedPolicy(value: unknown): NginxUnlimitedPolicy {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('nginx 不限速策略必须是对象')
  const candidate = value as { version?: unknown; unlimitedKeys?: unknown }
  if (candidate.version !== 1) throw new Error('nginx 不限速策略版本不受支持')
  if (!Array.isArray(candidate.unlimitedKeys)) throw new Error('nginx 不限速策略缺少 unlimitedKeys')
  return { version: 1, unlimitedKeys: normalizeKeys(candidate.unlimitedKeys) }
}

export function serializeNginxUnlimitedPolicy(policy: NginxUnlimitedPolicy): string {
  return `${JSON.stringify(parseNginxUnlimitedPolicy(policy))}\n`
}

export function nginxUnlimitedPolicyHash(policy: NginxUnlimitedPolicy): string {
  return crypto.createHash('sha256').update(serializeNginxUnlimitedPolicy(policy)).digest('hex')
}

export function buildNginxUnlimitedPolicyRequest(policy: NginxUnlimitedPolicy, requestId: string): NginxUnlimitedPolicyRequest {
  if (!/^[A-Za-z0-9-]{8,128}$/.test(requestId)) throw new Error('nginx 不限速策略 requestId 非法')
  const normalized = parseNginxUnlimitedPolicy(policy)
  return { ...normalized, requestId, policyHash: nginxUnlimitedPolicyHash(normalized) }
}

export function parseNginxUnlimitedPolicyRequest(value: unknown): NginxUnlimitedPolicyRequest {
  const policy = parseNginxUnlimitedPolicy(value)
  const candidate = value as { requestId?: unknown; policyHash?: unknown }
  if (typeof candidate.requestId !== 'string' || !/^[A-Za-z0-9-]{8,128}$/.test(candidate.requestId)) {
    throw new Error('nginx 不限速策略 requestId 非法')
  }
  if (typeof candidate.policyHash !== 'string' || !/^[a-f0-9]{64}$/.test(candidate.policyHash)) {
    throw new Error('nginx 不限速策略 policyHash 非法')
  }
  const expectedHash = nginxUnlimitedPolicyHash(policy)
  if (candidate.policyHash !== expectedHash) throw new Error('nginx 不限速策略哈希不匹配')
  return { ...policy, requestId: candidate.requestId, policyHash: candidate.policyHash }
}

export function renderNginxUnlimitedInclude(policy: NginxUnlimitedPolicy): string {
  const normalized = parseNginxUnlimitedPolicy(policy)
  const lines = ['# Generated by crosery-api-console. Do not edit.']
  for (const key of normalized.unlimitedKeys) {
    lines.push(
      `if ($http_authorization = "Bearer ${key}") {`,
      '    set $ibuki_perip_key "";',
      '}',
    )
  }
  return `${lines.join('\n')}\n`
}

export function writeNginxUnlimitedPolicySnapshot(filePath: string, request: NginxUnlimitedPolicyRequest, force = false): boolean {
  const content = `${JSON.stringify(parseNginxUnlimitedPolicyRequest(request))}\n`
  const directory = path.dirname(filePath)
  fs.mkdirSync(directory, { recursive: true, mode: 0o700 })
  fs.chmodSync(directory, 0o700)

  try {
    if (!force && fs.readFileSync(filePath, 'utf8') === content) {
      fs.chmodSync(filePath, 0o600)
      return false
    }
  } catch (error) {
    if (!(error instanceof Error && 'code' in error && error.code === 'ENOENT')) throw error
  }

  const temporary = path.join(directory, `.${path.basename(filePath)}.tmp-${process.pid}-${crypto.randomUUID()}`)
  let descriptor: number | undefined
  try {
    descriptor = fs.openSync(temporary, 'wx', 0o600)
    fs.writeFileSync(descriptor, content, 'utf8')
    fs.fsyncSync(descriptor)
    fs.closeSync(descriptor)
    descriptor = undefined
    fs.renameSync(temporary, filePath)
    fs.chmodSync(filePath, 0o600)
    return true
  } catch (error) {
    if (descriptor !== undefined) fs.closeSync(descriptor)
    try { fs.unlinkSync(temporary) } catch { /* preserve the original write error */ }
    throw error
  }
}
