import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'

import {
  buildNginxUnlimitedPolicy,
  buildNginxUnlimitedPolicyRequest,
  parseNginxUnlimitedPolicy,
  parseNginxUnlimitedPolicyRequest,
  renderNginxUnlimitedInclude,
  writeNginxUnlimitedPolicySnapshot,
} from './nginxUnlimitedPolicy.js'

const keyA = 'sk-alpha-0123456789abcdef'
const keyB = 'sk-beta-abcdef0123456789'

const row = (keyValue: string, enabled: boolean, totalConcurrency: number) => ({
  keyValue,
  enabled,
  totalConcurrency,
})

test('only enabled zero-concurrency keys enter the nginx unlimited policy', () => {
  const policy = buildNginxUnlimitedPolicy([
    row(keyB, true, 0),
    row(keyA, true, 0),
    row('sk-limited-0123456789abcdef', true, 5),
    row('sk-disabled-0123456789abcdef', false, 0),
    row(keyA, true, 0),
  ])

  assert.deepEqual(policy, { version: 1, unlimitedKeys: [keyA, keyB] })
})

test('rejects malformed or directive-injecting keys', () => {
  assert.throws(
    () => buildNginxUnlimitedPolicy([row('sk-safe-0123456789\nlimit_conn off;', true, 0)]),
    /API Key/,
  )
  assert.throws(
    () => parseNginxUnlimitedPolicy({ version: 1, unlimitedKeys: ['sk-safe-0123456789"; return 200; #'] }),
    /API Key/,
  )
})

test('parses a versioned policy and returns a normalized independent copy', () => {
  const raw = { version: 1, unlimitedKeys: [keyB, keyA, keyA] }
  const parsed = parseNginxUnlimitedPolicy(raw)
  assert.deepEqual(parsed, { version: 1, unlimitedKeys: [keyA, keyB] })
  raw.unlimitedKeys.push('sk-mutated-0123456789abcdef')
  assert.deepEqual(parsed, { version: 1, unlimitedKeys: [keyA, keyB] })
})

test('renders deterministic nginx set-only exemptions without exposing key comments', () => {
  const rendered = renderNginxUnlimitedInclude({ version: 1, unlimitedKeys: [keyB, keyA] })
  assert.equal(rendered, [
    '# Generated by crosery-api-console. Do not edit.',
    `if ($http_authorization = "Bearer ${keyA}") {`,
    '    set $ibuki_perip_key "";',
    '}',
    `if ($http_authorization = "Bearer ${keyB}") {`,
    '    set $ibuki_perip_key "";',
    '}',
    '',
  ].join('\n'))
  assert.equal(rendered.includes('$fangzhiyu_perip_key'), false)
  assert.equal(rendered.includes('limit_conn'), false)
})

test('policy requests bind requestId and policy hash', () => {
  const policy = { version: 1 as const, unlimitedKeys: [keyA] }
  const request = buildNginxUnlimitedPolicyRequest(policy, 'request-12345678')
  assert.deepEqual(parseNginxUnlimitedPolicyRequest(request), request)
  assert.throws(() => parseNginxUnlimitedPolicyRequest({ ...request, policyHash: '0'.repeat(64) }), /哈希/)
})

test('snapshot writes are atomic, mode 0600 and idempotent', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nginx-policy-'))
  const filePath = path.join(dir, 'nginx-unlimited-policy.json')
  const request = buildNginxUnlimitedPolicyRequest(
    { version: 1 as const, unlimitedKeys: [keyA] },
    'request-12345678',
  )

  assert.equal(writeNginxUnlimitedPolicySnapshot(filePath, request), true)
  assert.equal(fs.statSync(filePath).mode & 0o777, 0o600)
  const first = fs.readFileSync(filePath, 'utf8')
  assert.deepEqual(JSON.parse(first), request)
  assert.equal(writeNginxUnlimitedPolicySnapshot(filePath, request), false)
  assert.equal(fs.readFileSync(filePath, 'utf8'), first)
  assert.equal(fs.readdirSync(dir).some((name) => name.includes('.tmp-')), false)
})
