// Generated by scripts/magpie-upstream.mjs. Do not edit.

// Source shapes only: unknown means the wire contract was not statically proved.

// Upstream Magpie, Copyright (c) 2026 yetone, MIT. See deploy/magpie/upstream/LICENSE.

export const MAGPIE_API_REVISION = "3fe2ff99587e17dfe0ea707ffd0eccc088824433" as const

export const MAGPIE_LOGIN_AGENTS = ["antigravity","claude","codex","commandcode-plan","copilot","cursor","devin","dimagent","factory","gemini","grok","kiro","mimo-app","qoder","workbuddy","workbuddy-ai","zcode","zed"] as const

export const MAGPIE_API_ROUTES = [
  {
    "id": "inference * /backend-api/codex/",
    "surface": "inference",
    "method": "*",
    "path": "/backend-api/codex/",
    "actions": []
  },
  {
    "id": "inference * /",
    "surface": "inference",
    "method": "*",
    "path": "/",
    "actions": []
  },
  {
    "id": "inference GET /api/hello",
    "surface": "inference",
    "method": "GET",
    "path": "/api/hello",
    "actions": []
  },
  {
    "id": "inference GET /models",
    "surface": "inference",
    "method": "GET",
    "path": "/models",
    "actions": []
  },
  {
    "id": "inference GET /v1/magpie/quotas",
    "surface": "inference",
    "method": "GET",
    "path": "/v1/magpie/quotas",
    "actions": []
  },
  {
    "id": "inference GET /v1/models/{id...}",
    "surface": "inference",
    "method": "GET",
    "path": "/v1/models/{id...}",
    "actions": []
  },
  {
    "id": "inference GET /v1/models",
    "surface": "inference",
    "method": "GET",
    "path": "/v1/models",
    "actions": []
  },
  {
    "id": "inference GET /v1beta/models",
    "surface": "inference",
    "method": "GET",
    "path": "/v1beta/models",
    "actions": []
  },
  {
    "id": "inference GET /{$}",
    "surface": "inference",
    "method": "GET",
    "path": "/{$}",
    "actions": []
  },
  {
    "id": "inference POST /_magpie/claude-mcp/{token}",
    "surface": "inference",
    "method": "POST",
    "path": "/_magpie/claude-mcp/{token}",
    "actions": []
  },
  {
    "id": "inference POST /chat/completions",
    "surface": "inference",
    "method": "POST",
    "path": "/chat/completions",
    "actions": []
  },
  {
    "id": "inference POST /images/edits",
    "surface": "inference",
    "method": "POST",
    "path": "/images/edits",
    "actions": []
  },
  {
    "id": "inference POST /images/generations",
    "surface": "inference",
    "method": "POST",
    "path": "/images/generations",
    "actions": []
  },
  {
    "id": "inference POST /messages",
    "surface": "inference",
    "method": "POST",
    "path": "/messages",
    "actions": []
  },
  {
    "id": "inference POST /responses",
    "surface": "inference",
    "method": "POST",
    "path": "/responses",
    "actions": []
  },
  {
    "id": "inference POST /v1/chat/completions",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/chat/completions",
    "actions": []
  },
  {
    "id": "inference POST /v1/images/edits",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/images/edits",
    "actions": []
  },
  {
    "id": "inference POST /v1/images/generations",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/images/generations",
    "actions": []
  },
  {
    "id": "inference POST /v1/messages/count_tokens",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/messages/count_tokens",
    "actions": []
  },
  {
    "id": "inference POST /v1/messages",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/messages",
    "actions": []
  },
  {
    "id": "inference POST /v1/responses",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/responses",
    "actions": []
  },
  {
    "id": "inference POST /v1/systemone",
    "surface": "inference",
    "method": "POST",
    "path": "/v1/systemone",
    "actions": []
  },
  {
    "id": "inference POST /v1beta/models/{call...}",
    "surface": "inference",
    "method": "POST",
    "path": "/v1beta/models/{call...}",
    "actions": [
      "countTokens",
      "generateContent",
      "streamGenerateContent"
    ]
  },
  {
    "id": "management GET /api/agents/cli",
    "surface": "management",
    "method": "GET",
    "path": "/api/agents/cli",
    "actions": []
  },
  {
    "id": "management GET /api/davsync",
    "surface": "management",
    "method": "GET",
    "path": "/api/davsync",
    "actions": []
  },
  {
    "id": "management GET /api/drift",
    "surface": "management",
    "method": "GET",
    "path": "/api/drift",
    "actions": []
  },
  {
    "id": "management GET /api/gateway/history",
    "surface": "management",
    "method": "GET",
    "path": "/api/gateway/history",
    "actions": []
  },
  {
    "id": "management GET /api/gateway/trace",
    "surface": "management",
    "method": "GET",
    "path": "/api/gateway/trace",
    "actions": []
  },
  {
    "id": "management GET /api/groups",
    "surface": "management",
    "method": "GET",
    "path": "/api/groups",
    "actions": []
  },
  {
    "id": "management GET /api/icons/{name}",
    "surface": "management",
    "method": "GET",
    "path": "/api/icons/{name}",
    "actions": []
  },
  {
    "id": "management GET /api/import/{id}",
    "surface": "management",
    "method": "GET",
    "path": "/api/import/{id}",
    "actions": []
  },
  {
    "id": "management GET /api/importapps",
    "surface": "management",
    "method": "GET",
    "path": "/api/importapps",
    "actions": []
  },
  {
    "id": "management GET /api/library/icon",
    "surface": "management",
    "method": "GET",
    "path": "/api/library/icon",
    "actions": []
  },
  {
    "id": "management GET /api/library/market/servers",
    "surface": "management",
    "method": "GET",
    "path": "/api/library/market/servers",
    "actions": []
  },
  {
    "id": "management GET /api/library/market/skills",
    "surface": "management",
    "method": "GET",
    "path": "/api/library/market/skills",
    "actions": []
  },
  {
    "id": "management GET /api/library/rtk",
    "surface": "management",
    "method": "GET",
    "path": "/api/library/rtk",
    "actions": []
  },
  {
    "id": "management GET /api/library/skill",
    "surface": "management",
    "method": "GET",
    "path": "/api/library/skill",
    "actions": []
  },
  {
    "id": "management GET /api/library",
    "surface": "management",
    "method": "GET",
    "path": "/api/library",
    "actions": []
  },
  {
    "id": "management GET /api/login/usage",
    "surface": "management",
    "method": "GET",
    "path": "/api/login/usage",
    "actions": []
  },
  {
    "id": "management GET /api/omarchy/widget",
    "surface": "management",
    "method": "GET",
    "path": "/api/omarchy/widget",
    "actions": []
  },
  {
    "id": "management GET /api/omarchy",
    "surface": "management",
    "method": "GET",
    "path": "/api/omarchy",
    "actions": []
  },
  {
    "id": "management GET /api/providers",
    "surface": "management",
    "method": "GET",
    "path": "/api/providers",
    "actions": []
  },
  {
    "id": "management GET /api/sessions/one",
    "surface": "management",
    "method": "GET",
    "path": "/api/sessions/one",
    "actions": []
  },
  {
    "id": "management GET /api/sessions/overview",
    "surface": "management",
    "method": "GET",
    "path": "/api/sessions/overview",
    "actions": []
  },
  {
    "id": "management GET /api/sessions/progress",
    "surface": "management",
    "method": "GET",
    "path": "/api/sessions/progress",
    "actions": []
  },
  {
    "id": "management GET /api/sessions/stats",
    "surface": "management",
    "method": "GET",
    "path": "/api/sessions/stats",
    "actions": []
  },
  {
    "id": "management GET /api/sessions",
    "surface": "management",
    "method": "GET",
    "path": "/api/sessions",
    "actions": []
  },
  {
    "id": "management GET /api/settings",
    "surface": "management",
    "method": "GET",
    "path": "/api/settings",
    "actions": []
  },
  {
    "id": "management GET /api/signin/{id}",
    "surface": "management",
    "method": "GET",
    "path": "/api/signin/{id}",
    "actions": []
  },
  {
    "id": "management GET /api/state",
    "surface": "management",
    "method": "GET",
    "path": "/api/state",
    "actions": []
  },
  {
    "id": "management GET /api/update",
    "surface": "management",
    "method": "GET",
    "path": "/api/update",
    "actions": []
  },
  {
    "id": "management GET /api/usage/quotas",
    "surface": "management",
    "method": "GET",
    "path": "/api/usage/quotas",
    "actions": []
  },
  {
    "id": "management GET /api/usage/requests.csv",
    "surface": "management",
    "method": "GET",
    "path": "/api/usage/requests.csv",
    "actions": []
  },
  {
    "id": "management GET /api/usage/requests",
    "surface": "management",
    "method": "GET",
    "path": "/api/usage/requests",
    "actions": []
  },
  {
    "id": "management GET /api/usage",
    "surface": "management",
    "method": "GET",
    "path": "/api/usage",
    "actions": []
  },
  {
    "id": "management POST /api/agents/arrange",
    "surface": "management",
    "method": "POST",
    "path": "/api/agents/arrange",
    "actions": []
  },
  {
    "id": "management POST /api/agents/cli/{id}",
    "surface": "management",
    "method": "POST",
    "path": "/api/agents/cli/{id}",
    "actions": []
  },
  {
    "id": "management POST /api/agents/{action}/{id}",
    "surface": "management",
    "method": "POST",
    "path": "/api/agents/{action}/{id}",
    "actions": [
      "keep",
      "reapply"
    ]
  },
  {
    "id": "management POST /api/backup/export",
    "surface": "management",
    "method": "POST",
    "path": "/api/backup/export",
    "actions": []
  },
  {
    "id": "management POST /api/backup/import",
    "surface": "management",
    "method": "POST",
    "path": "/api/backup/import",
    "actions": []
  },
  {
    "id": "management POST /api/codex/daemon/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/codex/daemon/{action}",
    "actions": [
      "dismiss",
      "restart"
    ]
  },
  {
    "id": "management POST /api/copy",
    "surface": "management",
    "method": "POST",
    "path": "/api/copy",
    "actions": []
  },
  {
    "id": "management POST /api/davsync/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/davsync/{action}",
    "actions": [
      "dismiss",
      "now",
      "off",
      "reveal",
      "save"
    ]
  },
  {
    "id": "management POST /api/gateway/unrest",
    "surface": "management",
    "method": "POST",
    "path": "/api/gateway/unrest",
    "actions": []
  },
  {
    "id": "management POST /api/groups/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/groups/{action}",
    "actions": [
      "delete",
      "save",
      "show"
    ]
  },
  {
    "id": "management POST /api/icons/favicon",
    "surface": "management",
    "method": "POST",
    "path": "/api/icons/favicon",
    "actions": []
  },
  {
    "id": "management POST /api/icons",
    "surface": "management",
    "method": "POST",
    "path": "/api/icons",
    "actions": []
  },
  {
    "id": "management POST /api/import/icon",
    "surface": "management",
    "method": "POST",
    "path": "/api/import/icon",
    "actions": []
  },
  {
    "id": "management POST /api/importapps",
    "surface": "management",
    "method": "POST",
    "path": "/api/importapps",
    "actions": []
  },
  {
    "id": "management POST /api/keys/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/keys/{action}",
    "actions": [
      "add",
      "off",
      "on",
      "protocol",
      "remove",
      "rename",
      "use"
    ]
  },
  {
    "id": "management POST /api/library/market/about",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/market/about",
    "actions": []
  },
  {
    "id": "management POST /api/library/projects/choose",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/projects/choose",
    "actions": []
  },
  {
    "id": "management POST /api/library/reveal",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/reveal",
    "actions": []
  },
  {
    "id": "management POST /api/library/rtk/install",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/rtk/install",
    "actions": []
  },
  {
    "id": "management POST /api/library/rtk/upgrade",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/rtk/upgrade",
    "actions": []
  },
  {
    "id": "management POST /api/library/rtk",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/rtk",
    "actions": []
  },
  {
    "id": "management POST /api/library/skills/check",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/skills/check",
    "actions": []
  },
  {
    "id": "management POST /api/library/skills/probe",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/skills/probe",
    "actions": []
  },
  {
    "id": "management POST /api/library/{what}/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/library/{what}/{action}",
    "actions": [
      "all/sync",
      "instructions/import",
      "instructions/save",
      "market/server",
      "market/skill",
      "projects/add",
      "projects/copy",
      "projects/remove",
      "projects/skill",
      "servers/agents",
      "servers/import",
      "servers/remove",
      "servers/save",
      "skills/agents",
      "skills/import",
      "skills/install",
      "skills/remove",
      "skills/update",
      "skills/update-all",
      "skills/update-some"
    ]
  },
  {
    "id": "management POST /api/login/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/login/{action}",
    "actions": [
      "forget",
      "off",
      "on",
      "switch"
    ]
  },
  {
    "id": "management POST /api/omarchy/widget",
    "surface": "management",
    "method": "POST",
    "path": "/api/omarchy/widget",
    "actions": []
  },
  {
    "id": "management POST /api/open",
    "surface": "management",
    "method": "POST",
    "path": "/api/open",
    "actions": []
  },
  {
    "id": "management POST /api/profile/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/profile/{action}",
    "actions": [
      "delete",
      "save",
      "use"
    ]
  },
  {
    "id": "management POST /api/provider/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/provider/{action}",
    "actions": [
      "affinity",
      "balance",
      "delete",
      "efforts",
      "images",
      "key",
      "models",
      "name",
      "off",
      "on",
      "quiet",
      "route",
      "save",
      "show",
      "test",
      "unfetch"
    ]
  },
  {
    "id": "management POST /api/sessions/terminal",
    "surface": "management",
    "method": "POST",
    "path": "/api/sessions/terminal",
    "actions": []
  },
  {
    "id": "management POST /api/set",
    "surface": "management",
    "method": "POST",
    "path": "/api/set",
    "actions": []
  },
  {
    "id": "management POST /api/settings/lan",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/lan",
    "actions": []
  },
  {
    "id": "management POST /api/settings/login",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/login",
    "actions": []
  },
  {
    "id": "management POST /api/settings/quota-left",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/quota-left",
    "actions": []
  },
  {
    "id": "management POST /api/settings/redact-rules",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/redact-rules",
    "actions": []
  },
  {
    "id": "management POST /api/settings/reveal",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/reveal",
    "actions": []
  },
  {
    "id": "management POST /api/settings/text-size",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings/text-size",
    "actions": []
  },
  {
    "id": "management POST /api/settings",
    "surface": "management",
    "method": "POST",
    "path": "/api/settings",
    "actions": []
  },
  {
    "id": "management POST /api/signin/import",
    "surface": "management",
    "method": "POST",
    "path": "/api/signin/import",
    "actions": []
  },
  {
    "id": "management POST /api/signin/{id}/callback",
    "surface": "management",
    "method": "POST",
    "path": "/api/signin/{id}/callback",
    "actions": []
  },
  {
    "id": "management POST /api/signin/{id}/cancel",
    "surface": "management",
    "method": "POST",
    "path": "/api/signin/{id}/cancel",
    "actions": []
  },
  {
    "id": "management POST /api/signin",
    "surface": "management",
    "method": "POST",
    "path": "/api/signin",
    "actions": []
  },
  {
    "id": "management POST /api/stepfun/{site}/session",
    "surface": "management",
    "method": "POST",
    "path": "/api/stepfun/{site}/session",
    "actions": []
  },
  {
    "id": "management POST /api/stepfun/{site}/signout",
    "surface": "management",
    "method": "POST",
    "path": "/api/stepfun/{site}/signout",
    "actions": []
  },
  {
    "id": "management POST /api/sync",
    "surface": "management",
    "method": "POST",
    "path": "/api/sync",
    "actions": []
  },
  {
    "id": "management POST /api/update/check",
    "surface": "management",
    "method": "POST",
    "path": "/api/update/check",
    "actions": []
  },
  {
    "id": "management POST /api/update/install",
    "surface": "management",
    "method": "POST",
    "path": "/api/update/install",
    "actions": []
  },
  {
    "id": "management POST /api/usage/codex-reset",
    "surface": "management",
    "method": "POST",
    "path": "/api/usage/codex-reset",
    "actions": []
  },
  {
    "id": "management POST /api/usage/requests/export",
    "surface": "management",
    "method": "POST",
    "path": "/api/usage/requests/export",
    "actions": []
  },
  {
    "id": "management POST /api/window/{action}",
    "surface": "management",
    "method": "POST",
    "path": "/api/window/{action}",
    "actions": [
      "fit",
      "hide",
      "main",
      "quit",
      "tint"
    ]
  }
] as const

export type MagpieRouteId = typeof MAGPIE_API_ROUTES[number]["id"]

export type MagpieUpstreamRequests = {
  "inference * /backend-api/codex/": unknown
  "inference * /": unknown
  "inference GET /api/hello": unknown
  "inference GET /models": unknown
  "inference GET /v1/magpie/quotas": unknown
  "inference GET /v1/models/{id...}": unknown
  "inference GET /v1/models": unknown
  "inference GET /v1beta/models": unknown
  "inference GET /{$}": unknown
  "inference POST /_magpie/claude-mcp/{token}": unknown
  "inference POST /chat/completions": unknown
  "inference POST /images/edits": unknown
  "inference POST /images/generations": unknown
  "inference POST /messages": unknown
  "inference POST /responses": unknown
  "inference POST /v1/chat/completions": unknown
  "inference POST /v1/images/edits": unknown
  "inference POST /v1/images/generations": unknown
  "inference POST /v1/messages/count_tokens": unknown
  "inference POST /v1/messages": unknown
  "inference POST /v1/responses": unknown
  "inference POST /v1/systemone": unknown
  "inference POST /v1beta/models/{call...}": unknown
  "management GET /api/agents/cli": unknown
  "management GET /api/davsync": unknown
  "management GET /api/drift": unknown
  "management GET /api/gateway/history": unknown
  "management GET /api/gateway/trace": unknown
  "management GET /api/groups": unknown
  "management GET /api/icons/{name}": unknown
  "management GET /api/import/{id}": unknown
  "management GET /api/importapps": unknown
  "management GET /api/library/icon": unknown
  "management GET /api/library/market/servers": unknown
  "management GET /api/library/market/skills": unknown
  "management GET /api/library/rtk": unknown
  "management GET /api/library/skill": unknown
  "management GET /api/library": unknown
  "management GET /api/login/usage": unknown
  "management GET /api/omarchy/widget": unknown
  "management GET /api/omarchy": unknown
  "management GET /api/providers": unknown
  "management GET /api/sessions/one": unknown
  "management GET /api/sessions/overview": unknown
  "management GET /api/sessions/progress": unknown
  "management GET /api/sessions/stats": unknown
  "management GET /api/sessions": unknown
  "management GET /api/settings": unknown
  "management GET /api/signin/{id}": unknown
  "management GET /api/state": unknown
  "management GET /api/update": unknown
  "management GET /api/usage/quotas": unknown
  "management GET /api/usage/requests.csv": unknown
  "management GET /api/usage/requests": unknown
  "management GET /api/usage": unknown
  "management POST /api/agents/arrange": {
  "Order": (Array<string>) | null
  "Hidden": (Array<string>) | null
  "Shown": (Array<string>) | null
}
  "management POST /api/agents/cli/{id}": unknown
  "management POST /api/agents/{action}/{id}": unknown
  "management POST /api/backup/export": {
  "Pass": string
  "Keys": boolean
  "Library": (boolean) | null
}
  "management POST /api/backup/import": {
  "Data": string
  "Pass": string
  "Agents": boolean
  "Library": (boolean) | null
}
  "management POST /api/codex/daemon/{action}": unknown
  "management POST /api/copy": {
  "Text": string
}
  "management POST /api/davsync/{action}": unknown
  "management POST /api/gateway/unrest": {
  "key": string
}
  "management POST /api/groups/{action}": unknown
  "management POST /api/icons/favicon": {
  "URL": string
}
  "management POST /api/icons": unknown
  "management POST /api/import/icon": {
  "URL": string
}
  "management POST /api/importapps": {
  "Picks": (Array<Magpie_provider_AppPick>) | null
}
  "management POST /api/keys/{action}": {
  "ID": string
  "Key": string
  "Name": string
  "Ref": string
  "Protocol": Magpie_provider_Protocol
}
  "management POST /api/library/market/about": {
  "IDs": (Array<string>) | null
}
  "management POST /api/library/projects/choose": unknown
  "management POST /api/library/reveal": {
  "Path": string
}
  "management POST /api/library/rtk/install": unknown
  "management POST /api/library/rtk/upgrade": unknown
  "management POST /api/library/rtk": {
  "Agent": string
  "On": boolean
}
  "management POST /api/library/skills/check": unknown
  "management POST /api/library/skills/probe": {
  "Source": string
}
  "management POST /api/library/{what}/{action}": unknown
  "management POST /api/login/{action}": {
  "Agent": string
  "User": string
}
  "management POST /api/omarchy/widget": {
  "On": boolean
}
  "management POST /api/open": {
  "URL": string
}
  "management POST /api/profile/{action}": {
  "Name": string
}
  "management POST /api/provider/{action}": unknown
  "management POST /api/sessions/terminal": {
  "Agent": string
  "ID": string
}
  "management POST /api/set": {
  "Agent": string
  "Field": string
  "Value": string
}
  "management POST /api/settings/lan": {
  "On": boolean
  "NewKey": boolean
}
  "management POST /api/settings/login": {
  "On": boolean
}
  "management POST /api/settings/quota-left": {
  "On": boolean
}
  "management POST /api/settings/redact-rules": {
  "Rules": (Array<unknown>) | null
}
  "management POST /api/settings/reveal": unknown
  "management POST /api/settings/text-size": {
  "Size": number
}
  "management POST /api/settings": unknown
  "management POST /api/signin/import": {
  "Agent": string
  "Files": (Array<string>) | null
}
  "management POST /api/signin/{id}/callback": {
  "URL": string
}
  "management POST /api/signin/{id}/cancel": unknown
  "management POST /api/signin": {
  "Agent": string
  "Site": string
}
  "management POST /api/stepfun/{site}/session": {
  "Text": string
}
  "management POST /api/stepfun/{site}/signout": unknown
  "management POST /api/sync": unknown
  "management POST /api/update/check": unknown
  "management POST /api/update/install": unknown
  "management POST /api/usage/codex-reset": {
  "User": string
}
  "management POST /api/usage/requests/export": unknown
  "management POST /api/window/{action}": unknown
}

export type MagpieUpstreamResponses = {
  "inference * /backend-api/codex/": unknown
  "inference * /": unknown
  "inference GET /api/hello": unknown
  "inference GET /models": unknown
  "inference GET /v1/magpie/quotas": unknown
  "inference GET /v1/models/{id...}": unknown
  "inference GET /v1/models": unknown
  "inference GET /v1beta/models": unknown
  "inference GET /{$}": unknown
  "inference POST /_magpie/claude-mcp/{token}": unknown
  "inference POST /chat/completions": unknown
  "inference POST /images/edits": unknown
  "inference POST /images/generations": unknown
  "inference POST /messages": unknown
  "inference POST /responses": unknown
  "inference POST /v1/chat/completions": unknown
  "inference POST /v1/images/edits": unknown
  "inference POST /v1/images/generations": unknown
  "inference POST /v1/messages/count_tokens": unknown
  "inference POST /v1/messages": unknown
  "inference POST /v1/responses": unknown
  "inference POST /v1/systemone": unknown
  "inference POST /v1beta/models/{call...}": unknown
  "management GET /api/agents/cli": unknown
  "management GET /api/davsync": unknown
  "management GET /api/drift": unknown
  "management GET /api/gateway/history": unknown
  "management GET /api/gateway/trace": unknown
  "management GET /api/groups": Magpie_gui_groupsJSON
  "management GET /api/icons/{name}": unknown
  "management GET /api/import/{id}": unknown
  "management GET /api/importapps": unknown
  "management GET /api/library/icon": unknown
  "management GET /api/library/market/servers": unknown
  "management GET /api/library/market/skills": unknown
  "management GET /api/library/rtk": Magpie_library_RTKView
  "management GET /api/library/skill": unknown
  "management GET /api/library": Magpie_gui_libraryJSON
  "management GET /api/login/usage": unknown
  "management GET /api/omarchy/widget": unknown
  "management GET /api/omarchy": unknown
  "management GET /api/providers": Magpie_gui_providersJSON
  "management GET /api/sessions/one": unknown
  "management GET /api/sessions/overview": unknown
  "management GET /api/sessions/progress": unknown
  "management GET /api/sessions/stats": unknown
  "management GET /api/sessions": unknown
  "management GET /api/settings": Magpie_gui_settingsJSON
  "management GET /api/signin/{id}": Magpie_provider_SignInState
  "management GET /api/state": Magpie_gui_stateJSON
  "management GET /api/update": unknown
  "management GET /api/usage/quotas": unknown
  "management GET /api/usage/requests.csv": unknown
  "management GET /api/usage/requests": Magpie_gui_ledgerJSON
  "management GET /api/usage": Magpie_gui_usageJSON
  "management POST /api/agents/arrange": Magpie_gui_settingsJSON
  "management POST /api/agents/cli/{id}": unknown
  "management POST /api/agents/{action}/{id}": Magpie_gui_stateJSON
  "management POST /api/backup/export": unknown
  "management POST /api/backup/import": unknown
  "management POST /api/codex/daemon/{action}": Magpie_gui_providersJSON
  "management POST /api/copy": unknown
  "management POST /api/davsync/{action}": unknown
  "management POST /api/gateway/unrest": unknown
  "management POST /api/groups/{action}": Magpie_gui_groupsJSON
  "management POST /api/icons/favicon": unknown
  "management POST /api/icons": unknown
  "management POST /api/import/icon": unknown
  "management POST /api/importapps": unknown
  "management POST /api/keys/{action}": Magpie_gui_providersJSON
  "management POST /api/library/market/about": unknown
  "management POST /api/library/projects/choose": unknown
  "management POST /api/library/reveal": unknown
  "management POST /api/library/rtk/install": Magpie_library_RTKView
  "management POST /api/library/rtk/upgrade": Magpie_library_RTKView
  "management POST /api/library/rtk": Magpie_library_RTKView
  "management POST /api/library/skills/check": Magpie_gui_libraryJSON
  "management POST /api/library/skills/probe": Magpie_library_Probe
  "management POST /api/library/{what}/{action}": Magpie_gui_libraryJSON
  "management POST /api/login/{action}": Magpie_gui_providersJSON
  "management POST /api/omarchy/widget": unknown
  "management POST /api/open": unknown
  "management POST /api/profile/{action}": unknown
  "management POST /api/provider/{action}": Magpie_gui_providersJSON
  "management POST /api/sessions/terminal": unknown
  "management POST /api/set": Magpie_gui_stateJSON
  "management POST /api/settings/lan": Magpie_gui_settingsJSON
  "management POST /api/settings/login": Magpie_gui_settingsJSON
  "management POST /api/settings/quota-left": Magpie_gui_settingsJSON
  "management POST /api/settings/redact-rules": Magpie_gui_settingsJSON
  "management POST /api/settings/reveal": unknown
  "management POST /api/settings/text-size": Magpie_gui_settingsJSON
  "management POST /api/settings": Magpie_gui_settingsJSON
  "management POST /api/signin/import": unknown
  "management POST /api/signin/{id}/callback": unknown
  "management POST /api/signin/{id}/cancel": unknown
  "management POST /api/signin": Magpie_provider_SignInState
  "management POST /api/stepfun/{site}/session": Magpie_gui_providersJSON
  "management POST /api/stepfun/{site}/signout": Magpie_gui_providersJSON
  "management POST /api/sync": Magpie_gui_stateJSON
  "management POST /api/update/check": unknown
  "management POST /api/update/install": unknown
  "management POST /api/usage/codex-reset": Magpie_provider_ResetOutcome
  "management POST /api/usage/requests/export": unknown
  "management POST /api/window/{action}": unknown
}

export type Magpie_catalog_liveFile = {
  "fetched": string
  "base": string
  "models": (Array<Magpie_catalog_Model>) | null
}

export type Magpie_catalog_liveModel = {
  "id": string
  "name": string
  "display_name": string
  "modalities": {
  "input": (Array<string>) | null
}
  "supported_endpoints": (Array<string>) | null
  "context_length": unknown
}

export type Magpie_catalog_mdModel = {
  "id": string
  "name": string
  "release_date": string
  "temperature": (boolean) | null
  "reasoning_options": (Array<{
  "type": string
  "values": (Array<string>) | null
}>) | null
  "modalities": {
  "input": (Array<string>) | null
  "output": (Array<string>) | null
}
  "cost": (Magpie_catalog_Price) | null
  "provider": ({
  "npm": string
}) | null
  "limit": {
  "context": number
  "input": number
  "output": number
}
}

export type Magpie_catalog_mdProvider = {
  "id": string
  "name": string
  "env": (Array<string>) | null
  "models": (Record<string, Magpie_catalog_mdModel>) | null
}

export type Magpie_catalog_Model = {
  "ID": string
  "Name": string
  "Provider": string
  "Released": string
  "Efforts": (Array<string>) | null
  "Temperature": (boolean) | null
  "Price": (Magpie_catalog_Price) | null
  "Keys"?: (Array<string>) | null
  "APIs"?: (Array<string>) | null
  "Images"?: boolean
  "ImageInput"?: (boolean) | null
  "Context"?: number
  "MaxContext"?: number
  "Output"?: number
  "Fast"?: boolean
  "Draws"?: boolean
  "Free"?: boolean
}

export type Magpie_catalog_Price = {
  "input": number
  "output": number
  "cache_read": number
  "cache_write": number
}

export type Magpie_gateway_aBlock = {
  "type": string
  "text"?: string
  "source"?: ({
  "type": string
  "media_type": string
  "data": string
  "url": string
}) | null
  "id"?: string
  "name"?: string
  "input"?: unknown
  "tool_use_id"?: string
  "content"?: unknown
  "is_error"?: boolean
  "thinking"?: string
  "signature"?: string
  "cache_control"?: (Record<string, string>) | null
}

export type Magpie_gateway_Affinity = {
  "mode": string
  "turn": number
  "within"?: boolean
  "last"?: string
  "lastTurn"?: number
  "at"?: string
  "cacheRead"?: number
  "kept"?: boolean
  "why": string
}

export type Magpie_gateway_allowanceKey = Record<string, never>

export type Magpie_gateway_answerError = unknown

export type Magpie_gateway_anthropicDecoder = Record<string, never>

export type Magpie_gateway_anthropicEncoder = Record<string, never>

export type Magpie_gateway_aRequest = {
  "model": string
  "system"?: unknown
  "messages": (Array<{
  "role": string
  "content": unknown
}>) | null
  "tools"?: (Array<{
  "type"?: string
  "name": string
  "description"?: string
  "input_schema"?: unknown
}>) | null
  "tool_choice"?: ({
  "type": string
  "name"?: string
  "disable_parallel_tool_use"?: boolean
}) | null
  "max_tokens": number
  "temperature"?: (number) | null
  "top_p"?: (number) | null
  "stop_sequences"?: (Array<string>) | null
  "stream"?: boolean
  "thinking"?: ({
  "type": string
  "budget_tokens"?: number
}) | null
  "output_config"?: ({
  "effort"?: string
}) | null
}

export type Magpie_gateway_aUsage = {
  "input_tokens": number
  "output_tokens": number
  "cache_read_input_tokens": number
  "cache_creation_input_tokens": number
}

export type Magpie_gateway_before = {
  "Intent": string
  "Effort": string
}

export type Magpie_gateway_bridgeTool = {
  "name": string
  "description"?: string
  "inputSchema": unknown
}

export type Magpie_gateway_Call = {
  "time": string
  "agent": string
  "kind"?: string
  "model": string
  "provider": string
  "from": Magpie_provider_Protocol
  "to": Magpie_provider_Protocol
  "status": number
  "ms": number
  "ttft"?: number
  "firstText"?: number
  "error"?: string
  "fallback"?: string
  "usage": Magpie_gateway_Usage
  "requestBody"?: string
  "responseBody"?: string
  "requestTruncated"?: boolean
  "responseTruncated"?: boolean
}

export type Magpie_gateway_candidate = Record<string, never>

export type Magpie_gateway_capturedBody = Record<string, never>

export type Magpie_gateway_captureResponseWriter = unknown

export type Magpie_gateway_chatDecoder = Record<string, never>

export type Magpie_gateway_chatEncoder = Record<string, never>

export type Magpie_gateway_chatTidy = Record<string, never>

export type Magpie_gateway_Classified = {
  "by": string
  "intents": (Array<string>) | null
  "intent"?: string
  "after"?: string
  "effort"?: string
  "score"?: number
  "sure"?: number
  "cached"?: boolean
  "ms"?: number
  "error"?: string
  "afterEffort"?: string
}

export type Magpie_gateway_classifiedAs = Record<string, never>

export type Magpie_gateway_classifier = unknown

export type Magpie_gateway_classifyFailure = Record<string, never>

export type Magpie_gateway_cliUsage = {
  "input_tokens": number
  "output_tokens": number
  "cache_read_input_tokens": number
  "cache_creation_input_tokens": number
  "output_tokens_details": {
  "thinking_tokens": number
}
}

export type Magpie_gateway_cmdLine = {
  "type": string
  "text": string
  "toolCallId": string
  "toolName": string
  "input": unknown
  "args": unknown
  "providerExecuted": boolean
  "finishReason": string
  "rawFinishReason": string
  "totalUsage": ({
  "inputTokens": number
  "outputTokens": number
  "inputTokenDetails": ({
  "noCacheTokens": (number) | null
  "cacheReadTokens": number
  "cacheWriteTokens": number
}) | null
  "outputTokenDetails": ({
  "reasoningTokens": number
}) | null
}) | null
  "cacheWriteTokens": number
  "error": unknown
}

export type Magpie_gateway_cmdMessage = {
  "role": string
  "content": (Array<Magpie_gateway_cmdPart>) | null
}

export type Magpie_gateway_cmdOutput = {
  "type": string
  "value": string
}

export type Magpie_gateway_cmdPart = {
  "type": string
  "text"?: (string) | null
  "toolCallId"?: string
  "toolName"?: string
  "input"?: unknown
  "output"?: (Magpie_gateway_cmdOutput) | null
  "image"?: string
  "mimeType"?: string
}

export type Magpie_gateway_cmdTool = {
  "name": string
  "description": string
  "input_schema": unknown
}

export type Magpie_gateway_codeAssistDecoder = Record<string, never>

export type Magpie_gateway_collector = Record<string, never>

export type Magpie_gateway_connectMsg = Record<string, never>

export type Magpie_gateway_counted = Record<string, never>

export type Magpie_gateway_cRequest = {
  "model": string
  "messages": (Array<{
  "role": string
  "content": unknown
  "reasoning_content"?: string
  "tool_calls"?: (Array<Magpie_gateway_cToolCall>) | null
  "tool_call_id"?: string
}>) | null
  "tools"?: (Array<{
  "type": string
  "function": {
  "name": string
  "description"?: string
  "parameters"?: unknown
}
}>) | null
  "tool_choice"?: unknown
  "web_search_options"?: unknown
  "max_tokens"?: number
  "max_completion_tokens"?: number
  "temperature"?: (number) | null
  "top_p"?: (number) | null
  "stop"?: unknown
  "stream"?: boolean
  "reasoning_effort"?: string
  "parallel_tool_calls"?: (boolean) | null
  "service_tier"?: string
  "prompt_cache_key"?: string
}

export type Magpie_gateway_cToolCall = {
  "index"?: (number) | null
  "id"?: string
  "type"?: string
  "function": {
  "name"?: string
  "arguments"?: string
}
}

export type Magpie_gateway_cursorStream = Record<string, never>

export type Magpie_gateway_cUsage = {
  "prompt_tokens": number
  "completion_tokens": number
  "total_tokens": number
  "prompt_tokens_details"?: ({
  "cached_tokens": number
  "cache_write_tokens": number
}) | null
  "completion_tokens_details"?: ({
  "reasoning_tokens": number
}) | null
  "prompt_cache_hit_tokens": number
  "cached_tokens": number
  "cache_read_input_tokens": number
  "cache_creation_input_tokens": number
}

export type Magpie_gateway_dayFile = Record<string, never>

export type Magpie_gateway_describingKey = Record<string, never>

export type Magpie_gateway_devinDecoder = Record<string, never>

export type Magpie_gateway_devinMsg = Record<string, never>

export type Magpie_gateway_drawing = {
  "Model": string
  "Prompt": string
  "Size": string
  "Quality": string
  "Background": string
  "Format": string
  "N": number
  "Images": (Array<Magpie_gateway_picture>) | null
  "Mask": (Magpie_gateway_picture) | null
}

export type Magpie_gateway_drawn = {
  "Images": (Array<Magpie_gateway_picture>) | null
  "Text": string
  "Revised": string
  "Input": number
  "Output": number
}

export type Magpie_gateway_drawVia = number

export type Magpie_gateway_Event = {
  "Kind": Magpie_gateway_EventKind
  "Status": number
  "Text": string
  "ID": string
  "Name": string
  "MsgID": string
  "Model": string
  "Stop": string
  "Usage": Magpie_gateway_Usage
  "Hits": (Array<Magpie_gateway_Hit>) | null
}

export type Magpie_gateway_EventKind = number

export type Magpie_gateway_firstToken = Record<string, never>

export type Magpie_gateway_gContent = {
  "role"?: string
  "parts": (Array<Magpie_gateway_gPart>) | null
}

export type Magpie_gateway_geminiChunk = {
  "candidates": (Array<{
  "content": {
  "parts": (Array<Magpie_gateway_gPart>) | null
}
  "finishReason": string
}>) | null
  "usageMetadata": ({
  "promptTokenCount": number
  "candidatesTokenCount": number
  "thoughtsTokenCount": number
  "cachedContentTokenCount": number
}) | null
  "modelVersion": string
  "responseId": string
}

export type Magpie_gateway_geminiEncoder = Record<string, never>

export type Magpie_gateway_gPart = {
  "text"?: string
  "thought"?: boolean
  "thoughtSignature"?: string
  "inlineData"?: ({
  "mimeType": string
  "data": string
}) | null
  "fileData"?: ({
  "mimeType": string
  "fileUri": string
}) | null
  "functionCall"?: ({
  "id"?: string
  "name": string
  "args"?: unknown
}) | null
  "functionResponse"?: ({
  "id"?: string
  "name": string
  "response"?: unknown
}) | null
}

export type Magpie_gateway_gRequest = {
  "model": string
  "stream": boolean
  "contents": (Array<Magpie_gateway_gContent>) | null
  "systemInstruction"?: unknown
  "tools"?: (Array<{
  "functionDeclarations"?: (Array<{
  "name": string
  "description"?: string
  "parameters"?: unknown
  "parametersJsonSchema"?: unknown
}>) | null
  "googleSearch"?: unknown
  "google_search"?: unknown
}>) | null
  "toolConfig"?: ({
  "functionCallingConfig"?: ({
  "mode": string
  "allowedFunctionNames"?: (Array<string>) | null
}) | null
}) | null
  "generationConfig"?: ({
  "maxOutputTokens"?: number
  "temperature"?: (number) | null
  "topP"?: (number) | null
  "stopSequences"?: (Array<string>) | null
  "responseMimeType"?: string
  "responseSchema"?: unknown
  "responseJsonSchema"?: unknown
  "thinkingConfig"?: ({
  "thinkingBudget"?: (number) | null
  "thinkingLevel"?: string
  "includeThoughts"?: boolean
}) | null
}) | null
}

export type Magpie_gateway_GroupRef = {
  "id": string
  "name": string
  "routing": string
  "affinity": string
  "auto"?: boolean
  "members": (Array<string>) | null
  "subs"?: (Array<Magpie_gateway_SubGroup>) | null
  "via"?: (Array<string>) | null
}

export type Magpie_gateway_HistoryDay = {
  "day": string
  "requests": number
}

export type Magpie_gateway_Hit = {
  "title": string
  "url": string
}

export type Magpie_gateway_holdWriter = Record<string, never>

export type Magpie_gateway_imageAt = {
  "Src": string
  "Last": boolean
  "Tool": boolean
}

export type Magpie_gateway_Kind = string

export type Magpie_gateway_kiroAsst = {
  "content": string
  "toolUses"?: (Array<Magpie_gateway_kiroToolUse>) | null
}

export type Magpie_gateway_kiroDecoder = Record<string, never>

export type Magpie_gateway_kiroEntry = {
  "userInputMessage"?: (Magpie_gateway_kiroUser) | null
  "assistantResponseMessage"?: (Magpie_gateway_kiroAsst) | null
}

export type Magpie_gateway_kiroFrame = Record<string, never>

export type Magpie_gateway_kiroImage = {
  "format": string
  "source": {
  "bytes": string
}
}

export type Magpie_gateway_kiroText = {
  "text": string
}

export type Magpie_gateway_kiroThinkParser = Record<string, never>

export type Magpie_gateway_kiroTool = {
  "toolSpecification": {
  "name": string
  "description": string
  "inputSchema": {
  "json": unknown
}
}
}

export type Magpie_gateway_kiroToolResult = {
  "toolUseId": string
  "status": string
  "content": (Array<Magpie_gateway_kiroText>) | null
}

export type Magpie_gateway_kiroToolUse = {
  "name": string
  "toolUseId": string
  "input": unknown
}

export type Magpie_gateway_kiroUser = {
  "content": string
  "modelId": string
  "origin": string
  "images"?: (Array<Magpie_gateway_kiroImage>) | null
  "userInputMessageContext"?: (Magpie_gateway_kiroUserCtx) | null
}

export type Magpie_gateway_kiroUserCtx = {
  "tools"?: (Array<Magpie_gateway_kiroTool>) | null
  "toolResults"?: (Array<Magpie_gateway_kiroToolResult>) | null
}

export type Magpie_gateway_left = Record<string, never>

export type Magpie_gateway_levelling = Record<string, never>

export type Magpie_gateway_lockedWriter = Record<string, never>

export type Magpie_gateway_mcpToolResult = {
  "content": (Array<(Record<string, unknown>) | null>) | null
  "is_error"?: boolean
}

export type Magpie_gateway_Message = {
  "Role": string
  "Parts": (Array<Magpie_gateway_Part>) | null
}

export type Magpie_gateway_NestedRule = {
  "group": string
  "name": string
  "rule": (Magpie_gateway_RuleHit) | null
}

export type Magpie_gateway_nsTool = {
  "Namespace": string
  "Name": string
}

export type Magpie_gateway_Part = {
  "Kind": Magpie_gateway_Kind
  "Text": string
  "MediaType": string
  "Data": string
  "URL": string
  "ID": string
  "Name": string
  "Args": unknown
  "CallID": string
  "IsError": boolean
  "Images": (Array<Magpie_gateway_Part>) | null
  "Signature": string
  "Hits": (Array<Magpie_gateway_Hit>) | null
}

export type Magpie_gateway_pb = (string) | null

export type Magpie_gateway_pbField = Record<string, never>

export type Magpie_gateway_picture = {
  "Mime": string
  "Data": (string) | null
  "URL": string
}

export type Magpie_gateway_planned = Record<string, never>

export type Magpie_gateway_qoderCall = Record<string, never>

export type Magpie_gateway_qoderFrag = Record<string, never>

export type Magpie_gateway_qoderText = Record<string, never>

export type Magpie_gateway_recorder = Record<string, never>

export type Magpie_gateway_Request = {
  "Model": string
  "System": string
  "Messages": (Array<Magpie_gateway_Message>) | null
  "Tools": (Array<Magpie_gateway_Tool>) | null
  "ToolChoice": string
  "MaxTokens": number
  "Temp": (number) | null
  "TopP": (number) | null
  "Stop": (Array<string>) | null
  "Stream": boolean
  "Effort": string
  "Thinking": boolean
  "ThinkOff": boolean
  "Parallel": (boolean) | null
  "WebSearch": boolean
  "Fast": boolean
  "CacheKey": string
  "GeminiCompat": boolean
  "Namespaced": (Record<string, Magpie_gateway_nsTool>) | null
}

export type Magpie_gateway_responsesDecoder = Record<string, never>

export type Magpie_gateway_responsesEncoder = Record<string, never>

export type Magpie_gateway_Rest = {
  "why": string
  "status": number
  "until": string
  "by": string
  "failures"?: number
  "key"?: string
  "link"?: string
}

export type Magpie_gateway_Result = {
  "ID": string
  "Model": string
  "Parts": (Array<Magpie_gateway_Part>) | null
  "Stop": string
  "Usage": Magpie_gateway_Usage
}

export type Magpie_gateway_rItem = {
  "type"?: string
  "role"?: string
  "content"?: unknown
  "id"?: string
  "call_id"?: string
  "name"?: string
  "namespace"?: string
  "arguments"?: string
  "output"?: unknown
  "status"?: string
  "summary"?: (Array<Magpie_gateway_rText>) | null
  "encrypted_content"?: string
  "action"?: ({
  "query": string
  "sources": (Array<{
  "url": string
}>) | null
}) | null
}

export type Magpie_gateway_round = unknown

export type Magpie_gateway_Route = {
  "seq": number
  "id": number
  "time": string
  "agent": string
  "kind"?: string
  "model": string
  "effort"?: string
  "provider": string
  "group"?: (Magpie_gateway_GroupRef) | null
  "rule"?: (Magpie_gateway_RuleHit) | null
  "nested"?: (Array<Magpie_gateway_NestedRule>) | null
  "affinity"?: (Magpie_gateway_Affinity) | null
  "order": (Array<Magpie_gateway_Weighed>) | null
  "left"?: (Array<Magpie_gateway_Weighed>) | null
  "tries": (Array<Magpie_gateway_Try>) | null
  "done": boolean
  "status"?: number
  "error"?: string
  "ms"?: number
  "tokens"?: number
  "out"?: number
  "ttft"?: number
  "firstText"?: number
  "served"?: string
  "swapped"?: boolean
}

export type Magpie_gateway_rRequest = {
  "model": string
  "instructions"?: string
  "input": unknown
  "tools"?: (Array<Magpie_gateway_rTool>) | null
  "tool_choice"?: unknown
  "max_output_tokens"?: number
  "temperature"?: (number) | null
  "top_p"?: (number) | null
  "stream"?: boolean
  "parallel_tool_calls"?: (boolean) | null
  "service_tier"?: string
  "prompt_cache_key"?: string
  "reasoning"?: ({
  "effort"?: string
  "summary"?: string
}) | null
}

export type Magpie_gateway_rText = {
  "type": string
  "text": string
}

export type Magpie_gateway_rTool = {
  "type": string
  "name": string
  "description"?: string
  "parameters"?: unknown
  "tools"?: (Array<Magpie_gateway_rTool>) | null
}

export type Magpie_gateway_RuleHit = {
  "n": number
  "use"?: string
  "when"?: (Array<string>) | null
  "held"?: boolean
  "waits"?: boolean
  "grown"?: boolean
  "turn": number
  "tokens": number
  "images"?: boolean
  "effort"?: string
  "unready"?: boolean
  "then"?: (Array<string>) | null
  "instead"?: string
  "classified"?: (Magpie_gateway_Classified) | null
  "pick"?: string
  "compact"?: boolean
  "small"?: (Array<string>) | null
  "bare"?: boolean
}

export type Magpie_gateway_rUsage = {
  "input_tokens": number
  "output_tokens": number
  "total_tokens": number
  "input_tokens_details": {
  "cached_tokens": number
}
  "output_tokens_details": {
  "reasoning_tokens": number
}
}

export type Magpie_gateway_sealedItem = {
  "type": string
  "encrypted_content": string
}

export type Magpie_gateway_sealsRefused = Record<string, never>

export type Magpie_gateway_searchingKey = Record<string, never>

export type Magpie_gateway_Server = Record<string, never>

export type Magpie_gateway_sight = Record<string, never>

export type Magpie_gateway_sseWriter = Record<string, never>

export type Magpie_gateway_stick = Record<string, never>

export type Magpie_gateway_streamEncoder = unknown

export type Magpie_gateway_streamPart = {
  "type": string
  "text": string
  "thinking": string
  "content": (Array<{
  "text": string
  "refusal": string
}>) | null
  "summary": (Array<{
  "text": string
}>) | null
}

export type Magpie_gateway_SubGroup = {
  "id": string
  "name": string
  "routing": string
  "in": string
  "rules"?: number
}

export type Magpie_gateway_subscriptionBridge = Record<string, never>

export type Magpie_gateway_subscriptionRun = Record<string, never>

export type Magpie_gateway_tokenUse = Record<string, never>

export type Magpie_gateway_Tool = {
  "Name": string
  "Description": string
  "Schema": unknown
}

export type Magpie_gateway_Totals = {
  "requests": number
  "rerouted": number
  "errors": number
}

export type Magpie_gateway_trace = Record<string, never>

export type Magpie_gateway_TraceState = {
  "seq": number
  "routes": (Array<Magpie_gateway_Route>) | null
  "totals": Magpie_gateway_Totals
}

export type Magpie_gateway_Try = {
  "id": string
  "model"?: string
  "effort"?: string
  "picked"?: boolean
  "fixed"?: string
  "start": string
  "done": boolean
  "status"?: number
  "ms"?: number
  "ttft"?: number
  "firstText"?: number
  "served"?: string
  "swapped"?: boolean
  "fail"?: string
  "error"?: string
  "rest"?: (Magpie_gateway_Rest) | null
  "again"?: number
}

export type Magpie_gateway_turnRule = Record<string, never>

export type Magpie_gateway_Usage = {
  "input": number
  "output": number
  "cache_read": number
  "cache_write": number
  "reasoning": number
  "served"?: string
}

export type Magpie_gateway_usageSniffer = Record<string, never>

export type Magpie_gateway_verdict = {
  "Intent": string
  "Effort": string
  "Score": number
  "Sure": number
}

export type Magpie_gateway_Weighed = {
  "id": string
  "provider": string
  "name": string
  "icon"?: string
  "preset"?: string
  "who"?: string
  "kind": string
  "agent"?: string
  "plan"?: string
  "model": string
  "fixed"?: string
  "routing": string
  "fallback"?: boolean
  "shared"?: boolean
  "known"?: boolean
  "learns"?: boolean
  "used": number
  "renews"?: (Array<string>) | null
  "tokens"?: number
  "turn"?: boolean
  "fit"?: number
  "speaks"?: Magpie_provider_Protocol
  "rest"?: (Magpie_gateway_Rest) | null
  "unlisted"?: boolean
  "aside"?: boolean
  "via"?: (Array<string>) | null
}

export type Magpie_gateway_weighing = Record<string, never>

export type Magpie_gui_accountJSON = unknown

export type Magpie_gui_agentJSON = {
  "id": string
  "name": string
  "icon": string
  "path": string
  "fields": (Array<Magpie_gui_fieldJSON>) | null
  "drift"?: (unknown) | null
  "import"?: string
  "added"?: boolean
  "launch"?: string
}

export type Magpie_gui_agentUse = unknown

export type Magpie_gui_clientJSON = {
  "id": string
  "name": string
  "icon": string
}

export type Magpie_gui_excludedJSON = unknown

export type Magpie_gui_fieldJSON = {
  "key": string
  "label": string
  "value": string
  "options": (Array<unknown>) | null
}

export type Magpie_gui_fxJSON = {
  "rate": number
  "at"?: (string) | null
  "stale": boolean
}

export type Magpie_gui_gatewayJSON = {
  "url": string
  "running": boolean
  "mine": boolean
  "window": boolean
  "models": number
  "calls": (Array<Magpie_gateway_Call>) | null
  "groups": (Array<Magpie_gui_gwGroupJSON>) | null
}

export type Magpie_gui_Glide = {
  "MS": number
  "Curve": Array<number>
}

export type Magpie_gui_groupJSON = unknown

export type Magpie_gui_groupsJSON = {
  "groups": (Array<Magpie_gui_groupJSON>) | null
  "models": (Array<Magpie_gui_modelRef>) | null
  "pools": (Array<Magpie_gui_poolJSON>) | null
  "deciders": (Array<Magpie_gui_modelRef>) | null
}

export type Magpie_gui_gwGroupJSON = {
  "id": string
  "name": string
  "icons": (Array<string>) | null
  "providers": (Array<string>) | null
}

export type Magpie_gui_host = Record<string, never>

export type Magpie_gui_importJSON = {
  "provider": Magpie_provider_Provider
  "error"?: string
  "replaces"?: string
}

export type Magpie_gui_ledgerAgent = {
  "id": string
  "name": string
  "icon": string
}

export type Magpie_gui_ledgerJSON = unknown

export type Magpie_gui_ledgerRow = unknown

export type Magpie_gui_libraryJSON = unknown

export type Magpie_gui_marketJSON = {
  "items": unknown
  "error"?: string
}

export type Magpie_gui_memberJSON = {
  "id": string
  "ready": boolean
  "provider"?: string
  "name"?: string
  "icon"?: string
  "model"?: string
  "on": number
  "group"?: boolean
  "of"?: string
  "effort"?: string
  "context"?: number
  "images"?: boolean
}

export type Magpie_gui_modelJSON = {
  "id": string
  "name": string
  "default"?: string
  "kept"?: (Array<string>) | null
  "efforts"?: (Array<string>) | null
  "given"?: boolean
  "images": boolean
  "imageSet"?: boolean
  "on": boolean
  "context"?: number
  "max"?: number
  "free"?: boolean
}

export type Magpie_gui_modelRef = {
  "id": string
  "name": string
  "provider": string
  "providerName": string
  "icon"?: string
  "context"?: number
  "efforts"?: (Array<string>) | null
}

export type Magpie_gui_poolJSON = {
  "provider": string
  "name": string
  "icon"?: string
  "kind": string
  "who": (Array<string>) | null
  "routing": string
  "affinity": string
  "protocol"?: Magpie_provider_Protocol
}

export type Magpie_gui_presetJSON = unknown

export type Magpie_gui_profileJSON = {
  "name": string
  "summary": string
  "library"?: (Magpie_gui_profileLibraryJSON) | null
}

export type Magpie_gui_profileLibraryJSON = {
  "servers": number
  "skills": number
  "instructions": boolean
}

export type Magpie_gui_providerAgent = {
  "id": string
  "name": string
  "icon": string
  "current": boolean
  "model"?: string
  "group"?: string
}

export type Magpie_gui_providerJSON = {
  "id": string
  "name": string
  "icon": string
  "preset": string
  "host": string
  "chat": string
  "responses": string
  "anthropic": string
  "decide"?: string
  "catalog": string
  "website": string
  "keysUrl": string
  "headers"?: (Record<string, string>) | null
  "proxy": string
  "accountProxies"?: (Record<string, string>) | null
  "balanceURL"?: string
  "balancePath"?: string
  "modelsURL"?: string
  "balanceToken": {
  "takes": boolean
  "set": boolean
}
  "stepPlan"?: (Magpie_gui_stepPlanJSON) | null
  "zhipuTeam"?: (Magpie_provider_ZhipuTeam) | null
  "key": {
  "set": boolean
  "masked": string
  "optional": boolean
}
  "ready": boolean
  "chosen": (Array<string>) | null
  "fallback": (Array<string>) | null
  "routing": string
  "affinity": string
  "models": (Array<Magpie_gui_modelJSON>) | null
  "exposed": number
  "draws"?: number
  "drawIds"?: (Array<string>) | null
  "unlisted": boolean
  "off": boolean
  "contexts"?: (Record<string, number>) | null
  "fetched": string
  "agents": (Array<Magpie_gui_providerAgent>) | null
  "sponsored": boolean
  "keyList": (Array<Magpie_provider_KeyInfo>) | null
  "account"?: (Magpie_gui_accountJSON) | null
}

export type Magpie_gui_providersJSON = {
  "providers": (Array<Magpie_gui_providerJSON>) | null
  "presets": (Array<Magpie_gui_presetJSON>) | null
  "excluded": (Array<Magpie_gui_excludedJSON>) | null
  "gateway": Magpie_gui_gatewayJSON
  "codexDaemon"?: string
  "moved"?: (Array<unknown>) | null
}

export type Magpie_gui_remoteWindows = string

export type Magpie_gui_retryKey = Record<string, never>

export type Magpie_gui_sessionJSON = unknown

export type Magpie_gui_sessionsJSON = {
  "sessions": (Array<Magpie_gui_sessionJSON>) | null
  "terminal": boolean
  "dirs": (Array<string>) | null
}

export type Magpie_gui_settingsJSON = unknown

export type Magpie_gui_stateJSON = {
  "agents": (Array<Magpie_gui_agentJSON>) | null
  "clients": (Array<Magpie_gui_clientJSON>) | null
  "profiles": (Array<Magpie_gui_profileJSON>) | null
  "catalog": string
  "notice"?: string
  "settings": unknown
  "fx": Magpie_gui_fxJSON
}

export type Magpie_gui_statsKept = Record<string, never>

export type Magpie_gui_stepPlanJSON = {
  "site": string
  "signedIn": boolean
  "url": string
  "bookmarklet": string
}

export type Magpie_gui_terminalApp = {
  "id": string
  "name": string
  "path"?: string
}

export type Magpie_gui_terminalChoice = {
  "id": string
  "name": string
}

export type Magpie_gui_terminalDiscovery = {
  "apps": (Array<Magpie_gui_terminalApp>) | null
  "default": string
}

export type Magpie_gui_traceJSON = unknown

export type Magpie_gui_updateJSON = {
  "state": string
  "current": string
  "latest"?: string
  "notes"?: string
  "url"?: string
  "stuck"?: string
  "retry"?: boolean
  "error"?: string
  "done"?: number
  "total"?: number
}

export type Magpie_gui_updater = Record<string, never>

export type Magpie_gui_usageGroup = unknown

export type Magpie_gui_usageJSON = unknown

export type Magpie_gui_Web = {
  "Addr": string
  "Link": string
}

export type Magpie_gui_webHost = Record<string, never>

export type Magpie_gui_Windows = unknown

export type Magpie_library_AgentInstructions = {
  "agent": string
  "name": string
  "icon": string
  "path": string
  "on": boolean
  "extra": string
  "own": number
  "edited"?: boolean
  "override"?: string
}

export type Magpie_library_AgentView = {
  "id": string
  "name": string
  "icon": string
  "instructions"?: string
  "mcp"?: string
  "skills"?: string
  "projectSkills"?: string
  "skillsAlso"?: (Array<string>) | null
  "note"?: string
  "noSSE"?: boolean
  "noRemote"?: boolean
  "mcpVia"?: string
}

export type Magpie_library_Applied = {
  "instructions"?: boolean
  "instrHash"?: string
  "mcp"?: (Array<string>) | null
  "skills"?: (Array<string>) | null
}

export type Magpie_library_backups = Record<string, never>

export type Magpie_library_Bundle = {
  "instructions": Magpie_library_Instructions
  "texts"?: (Record<string, string>) | null
  "extra"?: (Record<string, string>) | null
  "mcp": (Array<(Magpie_library_Server) | null>) | null
  "skills": (Array<(Magpie_library_CarriedSkill) | null>) | null
  "icons"?: (Record<string, string>) | null
}

export type Magpie_library_Candidate = {
  "path": string
  "name": string
  "description": string
  "have": boolean
}

export type Magpie_library_CarriedSkill = {
  "name": string
  "source"?: (Magpie_library_Source) | null
  "agents": (Array<string>) | null
  "files": (Record<string, (string) | null>) | null
  "exec"?: (Array<string>) | null
  "left"?: (Array<string>) | null
}

export type Magpie_library_commit = {
  "sha": string
  "html_url": string
  "commit": {
  "message": string
  "committer": {
  "date": string
}
}
}

export type Magpie_library_dshJS = string

export type Magpie_library_dshPatches = Record<string, never>

export type Magpie_library_dshRow = Record<string, never>

export type Magpie_library_errLimited = Record<string, never>

export type Magpie_library_fetched = Record<string, never>

export type Magpie_library_fetcher = Record<string, never>

export type Magpie_library_Found = {
  "server": (Magpie_library_Server) | null
  "others"?: (Array<string>) | null
  "icon"?: string
  "own"?: boolean
}

export type Magpie_library_FoundSkill = {
  "name": string
  "description": string
  "agents": (Array<string>) | null
  "others"?: (Array<string>) | null
  "link"?: string
  "shared"?: string
}

export type Magpie_library_Input = {
  "key": string
  "where": string
  "label": string
  "description"?: string
  "placeholder"?: string
  "secret"?: boolean
  "required"?: boolean
}

export type Magpie_library_InstrSet = {
  "id": string
  "name": string
}

export type Magpie_library_Instructions = {
  "agents": (Array<string>) | null
  "sets"?: (Array<Magpie_library_InstrSet>) | null
  "active"?: string
}

export type Magpie_library_InstructionsChange = {
  "shared"?: (string) | null
  "agents"?: (Array<string>) | null
  "extra"?: (Record<string, (string) | null>) | null
  "rewrite"?: (Array<string>) | null
  "texts"?: (Record<string, (string) | null>) | null
  "activate"?: string
  "create"?: (Magpie_library_InstrSet) | null
  "rename"?: (Magpie_library_InstrSet) | null
  "remove"?: string
}

export type Magpie_library_InstructionsView = {
  "shared": string
  "sets": (Array<Magpie_library_SetView>) | null
  "agents": (Array<Magpie_library_AgentInstructions>) | null
}

export type Magpie_library_kv = Record<string, never>

export type Magpie_library_Library = {
  "instructions": Magpie_library_Instructions
  "mcp": (Array<(Magpie_library_Server) | null>) | null
  "skills": (Array<(Magpie_library_Skill) | null>) | null
  "projects"?: (Array<(Magpie_library_Project) | null>) | null
  "applied"?: (Record<string, (Magpie_library_Applied) | null>) | null
  "icons"?: (Record<string, string>) | null
}

export type Magpie_library_MarketServer = {
  "id": string
  "name": string
  "title": string
  "description": string
  "publisher"?: string
  "icon"?: string
  "homepage"?: string
  "transport": string
  "runs"?: string
  "signIn"?: boolean
  "featured"?: boolean
  "optIn"?: boolean
  "inputs": (Array<Magpie_library_Input>) | null
  "have"?: string
}

export type Magpie_library_MarketSkill = {
  "id": string
  "source": string
  "skillId": string
  "name": string
  "installs": number
  "official"?: boolean
  "icon": string
  "description"?: string
  "have"?: string
}

export type Magpie_library_mcpFile = {
  "Path": string
  "Format": Magpie_library_mcpFormat
  "Also": (Array<string>) | null
  "Extra": (Array<string>) | null
}

export type Magpie_library_mcpFormat = number

export type Magpie_library_meta = {
  "name": string
  "description": string
}

export type Magpie_library_ordered = unknown

export type Magpie_library_piPlugins = Record<string, never>

export type Magpie_library_Probe = {
  "source": string
  "kind": string
  "candidates": (Array<Magpie_library_Candidate>) | null
}

export type Magpie_library_probeEntry = Record<string, never>

export type Magpie_library_Problem = {
  "agent": string
  "what": string
  "error": string
}

export type Magpie_library_Project = {
  "dir": string
  "copy"?: boolean
  "skills"?: (Record<string, (Array<string>) | null>) | null
  "placed"?: (Array<string>) | null
  "made"?: (Array<string>) | null
  "gitignore"?: boolean
}

export type Magpie_library_ProjectView = {
  "dir": string
  "name": string
  "copy": boolean
  "skills": (Record<string, (Array<string>) | null>) | null
  "placed": (Array<string>) | null
  "missing"?: boolean
  "problems"?: (Record<string, string>) | null
}

export type Magpie_library_registryServer = {
  "name": string
  "title": string
  "description": string
  "websiteUrl": string
  "repository": {
  "url": string
}
  "icons": (Array<{
  "src": string
}>) | null
  "remotes": (Array<{
  "type": string
  "url": string
  "headers": (Array<Magpie_library_registryVar>) | null
}>) | null
  "packages": (Array<{
  "registryType": string
  "identifier": string
  "transport": {
  "Type": string
}
  "environmentVariables": (Array<Magpie_library_registryVar>) | null
  "packageArguments": (Array<{
  "type": string
  "name": string
  "value": string
  "default": string
  "valueHint": string
  "description": string
  "isRequired": boolean
}>) | null
}>) | null
}

export type Magpie_library_registryVar = {
  "name": string
  "value": string
  "description": string
  "isRequired": boolean
  "isSecret": boolean
}

export type Magpie_library_Result = {
  "changed": (Array<string>) | null
  "problems": (Array<Magpie_library_Problem>) | null
  "backup"?: string
  "missing"?: (Array<string>) | null
  "updated"?: (Array<string>) | null
  "unupdated"?: (Array<Magpie_library_Problem>) | null
}

export type Magpie_library_RTKAgent = {
  "id": string
  "name": string
  "icon": string
  "on": boolean
  "blocked"?: string
}

export type Magpie_library_RTKDay = {
  "date": string
  "commands": number
  "input": number
  "saved": number
  "pct": number
}

export type Magpie_library_RTKGain = {
  "commands": number
  "input": number
  "saved": number
  "pct": number
}

export type Magpie_library_rtkSpec = Record<string, never>

export type Magpie_library_RTKView = {
  "path"?: string
  "version"?: string
  "gain"?: (Magpie_library_RTKGain) | null
  "days"?: (Array<Magpie_library_RTKDay>) | null
  "latest"?: string
  "upgrade"?: string
  "note"?: string
  "agents": (Array<Magpie_library_RTKAgent>) | null
  "url": string
  "install"?: string
  "restart"?: (Array<string>) | null
  "backup"?: string
}

export type Magpie_library_Server = {
  "name": string
  "transport": string
  "command"?: string
  "args"?: (Array<string>) | null
  "env"?: (Record<string, string>) | null
  "url"?: string
  "headers"?: (Record<string, string>) | null
  "agents": (Array<string>) | null
}

export type Magpie_library_ServerView = unknown

export type Magpie_library_Setup = {
  "instructions": Magpie_library_SetupInstructions
  "mcp": (Record<string, (Array<string>) | null>) | null
  "skills": (Record<string, (Array<string>) | null>) | null
}

export type Magpie_library_SetupInstructions = {
  "set"?: string
  "shared"?: string
  "agents": (Array<string>) | null
  "extra"?: (Record<string, string>) | null
}

export type Magpie_library_SetView = {
  "id": string
  "name": string
  "text": string
  "active"?: boolean
}

export type Magpie_library_Skill = {
  "name": string
  "source"?: (Magpie_library_Source) | null
  "agents": (Array<string>) | null
  "hash"?: string
  "commit"?: string
}

export type Magpie_library_SkillCheck = {
  "name": string
  "status": string
  "commit"?: string
  "date"?: string
  "message"?: string
  "url"?: string
  "error"?: string
}

export type Magpie_library_skillsShEntry = {
  "source": string
  "skillId": string
  "name": string
  "installs": number
  "isOfficial"?: boolean
}

export type Magpie_library_skillUpdate = Record<string, never>

export type Magpie_library_SkillView = {
  "name": string
  "description": string
  "source"?: string
  "kind": string
  "origin"?: string
  "icon"?: string
  "agents": (Array<string>) | null
  "missing"?: boolean
  "problems"?: (Record<string, string>) | null
  "check"?: (Magpie_library_SkillCheck) | null
}

export type Magpie_library_Source = {
  "kind": string
  "repo"?: string
  "ref"?: string
  "path"?: string
  "dir"?: string
}

export type Magpie_library_Target = {
  "Agent": (unknown) | null
  "Instructions": string
  "Override": string
  "MCP": (Magpie_library_mcpFile) | null
  "Skills": string
  "SkillsAlso": (Array<string>) | null
  "MCPVia": string
  "Note": string
}

export type Magpie_library_View = {
  "agents": (Array<Magpie_library_AgentView>) | null
  "servers": (Array<Magpie_library_ServerView>) | null
  "foundServers": (Array<Magpie_library_Found>) | null
  "skills": (Array<Magpie_library_SkillView>) | null
  "foundSkills": (Array<Magpie_library_FoundSkill>) | null
  "projects": (Array<Magpie_library_ProjectView>) | null
  "instructions": (Magpie_library_InstructionsView) | null
  "dir": string
  "backups": string
}

export type Magpie_provider_Account = {
  "agent": string
  "user": string
  "plan"?: string
}

export type Magpie_provider_accountStatusError = Record<string, never>

export type Magpie_provider_agentCLI = {
  "Name": string
}

export type Magpie_provider_Allowance = (Array<Magpie_provider_Limit>) | null

export type Magpie_provider_antigravityFamily = Record<string, never>

export type Magpie_provider_AppImport = {
  "ref": string
  "from"?: string
  "provider": Magpie_provider_Provider
  "status": string
  "existing"?: string
  "keyOf"?: string
  "off"?: string
  "skip"?: string
}

export type Magpie_provider_AppPick = {
  "source": string
  "ref": string
  "mode"?: string
}

export type Magpie_provider_AppSource = {
  "id": string
  "name": string
  "path": string
  "found": boolean
  "error"?: string
  "items": (Array<Magpie_provider_AppImport>) | null
}

export type Magpie_provider_balanceExpr = Record<string, never>

export type Magpie_provider_balanceSource = Record<string, never>

export type Magpie_provider_ccEntry = Record<string, never>

export type Magpie_provider_claudeAuth = {
  "accessToken": string
  "refreshToken": string
  "expiresAt": number
  "refreshTokenExpiresAt": number
  "scopes": (Array<string>) | null
  "subscriptionType": string
  "rateLimitTier": string
}

export type Magpie_provider_claudeCredentialLocation = Record<string, never>

export type Magpie_provider_claudeCredentials = {
  "OAuth": Magpie_provider_claudeAuth
}

export type Magpie_provider_ClaudeLimit = {
  "Kind": string
  "Used": number
  "ResetsAt": number
}

export type Magpie_provider_claudeProfileInfo = {
  "account": {
  "uuid": string
  "email": string
  "display_name": string
}
  "organization": {
  "uuid": string
  "name": string
  "organization_type": string
  "rate_limit_tier": string
  "billing_type": string
  "has_extra_usage_enabled": boolean
}
}

export type Magpie_provider_claudeUsageEntry = Record<string, never>

export type Magpie_provider_cliIdentity = unknown

export type Magpie_provider_cmdAuth = {
  "apiKey": string
  "userId"?: string
  "userName"?: string
  "keyName"?: string
}

export type Magpie_provider_cmdCredits = {
  "credits": {
  "planId": string
  "monthlyCredits": unknown
  "purchasedCredits": unknown
  "freeCredits": unknown
}
  "windowLimits": ({
  "fiveHour": (Magpie_provider_cmdWindow) | null
  "weekly": (Magpie_provider_cmdWindow) | null
}) | null
}

export type Magpie_provider_cmdLogin = unknown

export type Magpie_provider_cmdSeen = Record<string, never>

export type Magpie_provider_cmdWindow = {
  "used": unknown
  "cap": unknown
  "resetAt": unknown
}

export type Magpie_provider_codeAssistTier = {
  "id": string
  "name": string
  "isDefault": boolean
  "userDefinedCloudaicompanionProject": boolean
}

export type Magpie_provider_codexAuth = {
  "auth_mode": string
  "tokens": {
  "id_token": string
  "access_token": string
  "refresh_token": string
  "account_id": string
}
}

export type Magpie_provider_codexResetCreditsWire = {
  "available_count": number
  "credits": (Array<{
  "id": string
  "reset_type": string
  "status": string
  "granted_at": string
  "expires_at": (string) | null
}>) | null
}

export type Magpie_provider_CodexWarm = {
  "user": string
  "windows": (Array<string>) | null
  "error"?: string
}

export type Magpie_provider_codexWarmer = Record<string, never>

export type Magpie_provider_codexWindow = {
  "used_percent": number
  "limit_window_seconds": number
  "reset_at": number
  "reset_after_seconds": number
}

export type Magpie_provider_companionProject = string

export type Magpie_provider_copilotApp = {
  "user": string
  "oauth_token": string
}

export type Magpie_provider_copilotAutoKey = Record<string, never>

export type Magpie_provider_copilotAutoSession = {
  "Token": string
  "Model": string
  "ExpiresAt": number
}

export type Magpie_provider_copilotCLIUser = {
  "host": string
  "login": string
}

export type Magpie_provider_copilotLoginApp = unknown

export type Magpie_provider_copilotQuotaWire = {
  "has_quota": boolean
  "entitlement": number
  "quota_remaining": number
}

export type Magpie_provider_copilotSession = {
  "token": string
  "expires_at": number
  "endpoints": {
  "api": string
}
}

export type Magpie_provider_cursorFamily = Record<string, never>

export type Magpie_provider_decideRouteError = Record<string, never>

export type Magpie_provider_DevinFamily = {
  "UID": string
  "Label": string
  "Aliases": (Array<string>) | null
  "Models": (Array<Magpie_catalog_Model>) | null
}

export type Magpie_provider_devinLogin = unknown

export type Magpie_provider_devinNoWaitKey = Record<string, never>

export type Magpie_provider_dimagentCallback = {
  "Code": string
  "State": string
  "Error": string
}

export type Magpie_provider_dimagentCreds = {
  "uid": string
  "accessToken": string
  "refreshToken": string
  "expiresAt": number
  "sub"?: string
  "nickname"?: string
  "plan"?: string
  "models"?: unknown
}

export type Magpie_provider_dimagentLogin = unknown

export type Magpie_provider_endpoints = Record<string, never>

export type Magpie_provider_Entry = {
  "id": string
  "model": string
  "name": string
  "default"?: string
  "efforts"?: (Array<string>) | null
  "group"?: string
  "images"?: boolean
  "context"?: number
  "output"?: number
  "family"?: string
  "free"?: boolean
}

export type Magpie_provider_Exclusion = {
  "agent": string
  "provider"?: string
  "why": string
  "signedOut"?: boolean
  "quiet"?: boolean
}

export type Magpie_provider_factoryCreds = {
  "accessToken": string
  "refreshToken": string
  "expiresAt": number
  "orgId"?: string
  "activeOrganizationId"?: string
  "email"?: string
  "userId"?: string
  "region"?: string
}

export type Magpie_provider_factoryLimits = {
  "limits": {
  "standard": (Magpie_provider_factoryPool) | null
  "core": (Magpie_provider_factoryPool) | null
}
  "extraUsageBalanceCents": (number) | null
  "extraUsageAllowed": boolean
}

export type Magpie_provider_factoryLogin = unknown

export type Magpie_provider_factoryModel = Record<string, never>

export type Magpie_provider_factoryPool = {
  "fiveHour": (Magpie_provider_factoryWindow) | null
  "weekly": (Magpie_provider_factoryWindow) | null
  "monthly": (Magpie_provider_factoryWindow) | null
}

export type Magpie_provider_factoryStatus = {
  "Code": number
  "Msg": string
}

export type Magpie_provider_factoryTokens = {
  "access_token": string
  "refresh_token": string
  "organization_id": string
  "user": {
  "id": string
  "email": string
}
  "error": string
  "error_description": string
}

export type Magpie_provider_factoryWindow = {
  "usedPercent": number
  "windowEnd": unknown
}

export type Magpie_provider_file = {
  "providers": (Array<Magpie_provider_Provider>) | null
  "groups"?: (Array<Magpie_provider_Group>) | null
}

export type Magpie_provider_geminiFlags = Record<string, never>

export type Magpie_provider_googleAccount = Record<string, never>

export type Magpie_provider_googleApp = Record<string, never>

export type Magpie_provider_googleAuth = {
  "access_token"?: string
  "refresh_token": string
  "expiry_date"?: number
  "project"?: string
}

export type Magpie_provider_googleImport = Record<string, never>

export type Magpie_provider_googleLogin = unknown

export type Magpie_provider_googleModelInfo = unknown

export type Magpie_provider_googleProject = Record<string, never>

export type Magpie_provider_grokAmount = {
  "val": number
}

export type Magpie_provider_grokCandidate = Record<string, never>

export type Magpie_provider_grokCredential = {
  "key": string
  "email": string
  "expires_at": string
  "oidc_issuer": string
}

export type Magpie_provider_grokLogin = unknown

export type Magpie_provider_Group = {
  "id": string
  "name": string
  "members": (Array<string>) | null
  "routing"?: string
  "affinity"?: string
  "rules"?: (Array<Magpie_provider_Rule>) | null
  "classifier"?: string
  "effort"?: string
  "context"?: number
  "family"?: string
  "auto"?: boolean
  "hidden"?: boolean
}

export type Magpie_provider_ImportedAccount = {
  "user": string
  "status": string
  "plan"?: string
  "error"?: string
}

export type Magpie_provider_keptIdentity = {
  "user"?: string
  "plan"?: string
  "ok": boolean
}

export type Magpie_provider_KeyAccount = {
  "name"?: string
  "key": string
  "off"?: boolean
  "protocol"?: Magpie_provider_Protocol
}

export type Magpie_provider_KeyInfo = {
  "id": string
  "name"?: string
  "masked": string
  "active": boolean
  "on": boolean
  "protocol"?: Magpie_provider_Protocol
}

export type Magpie_provider_Kind = string

export type Magpie_provider_KiroAuth = {
  "Token": string
  "TokenType": string
  "Profile": string
  "Region": string
}

export type Magpie_provider_kiroCred = Record<string, never>

export type Magpie_provider_kiroFlow = Record<string, never>

export type Magpie_provider_kiroLimits = {
  "subscriptionInfo": {
  "subscriptionTitle": string
}
  "userInfo": {
  "email": string
}
  "usageBreakdownList": (Array<{
  "displayName": string
  "displayNamePlural": string
  "currentUsageWithPrecision": number
  "usageLimitWithPrecision": number
  "nextDateReset": number
  "freeTrialInfo": ({
  "freeTrialStatus": string
  "currentUsageWithPrecision": number
  "usageLimitWithPrecision": number
  "freeTrialExpiry": number
}) | null
}>) | null
  "nextDateReset": number
}

export type Magpie_provider_kiroLogin = unknown

export type Magpie_provider_kiroModelList = {
  "models": (Array<{
  "modelId": string
  "modelName": string
  "supportedInputTypes": (Array<string>) | null
  "tokenLimits": {
  "maxInputTokens": number
  "maxOutputTokens": number
}
}>) | null
  "defaultModel": {
  "modelId": string
}
}

export type Magpie_provider_kiroSaid = Record<string, never>

export type Magpie_provider_kiroSaved = {
  "accessToken": string
  "refreshToken": string
  "expiresAt": string
  "authMethod": string
  "provider": string
  "region"?: string
  "profileArn"?: string
  "clientId"?: string
  "clientSecret"?: string
}

export type Magpie_provider_kiroStatusError = Record<string, never>

export type Magpie_provider_lastQuota = {
  "at": string
  "quota": Magpie_provider_SubscriptionQuota
  "spans"?: (Array<Magpie_provider_lastWindow>) | null
}

export type Magpie_provider_lastWindow = {
  "span"?: unknown
  "model"?: string
  "aside"?: boolean
}

export type Magpie_provider_leftDaemon = Record<string, never>

export type Magpie_provider_Limit = {
  "Used": number
  "Resets": string
  "Span": unknown
  "Model": string
}

export type Magpie_provider_loadCodeAssistReply = {
  "currentTier": (Magpie_provider_codeAssistTier) | null
  "paidTier": (Magpie_provider_codeAssistTier) | null
  "allowedTiers": (Array<Magpie_provider_codeAssistTier>) | null
  "cloudaicompanionProject": Magpie_provider_companionProject
  "ineligibleTiers": (Array<{
  "reasonCode": string
  "reasonMessage": string
  "tierId": string
}>) | null
}

export type Magpie_provider_Login = {
  "agent": string
  "user": string
  "plan"?: string
  "seen": string
  "active": boolean
  "on": boolean
  "lapsed"?: string
  "own"?: boolean
}

export type Magpie_provider_loginImport = Record<string, never>

export type Magpie_provider_loginUsageEntry = Record<string, never>

export type Magpie_provider_Member = {
  "ID": string
  "Path": (Array<string>) | null
  "Via": (Array<Magpie_provider_Group>) | null
  "Provider": Magpie_provider_Provider
  "Model": string
  "Effort": string
}

export type Magpie_provider_mimoCreds = {
  "userId": string
  "cUserId"?: string
  "passToken": string
  "deviceId": string
  "region"?: string
  "base": string
  "cookies"?: (Record<string, string>) | null
  "issued": string
  "name"?: string
}

export type Magpie_provider_mimoLogin = unknown

export type Magpie_provider_mimoLongPoll = {
  "code": number
  "loginUrl": string
  "qr": string
  "lp": string
  "timeout": number
  "desc": string
}

export type Magpie_provider_mimoMe = {
  "code": number
  "data": {
  "userId": unknown
  "nickname": string
  "nickName": string
  "name": string
  "displayName": string
  "userName": string
  "region": string
  "country": string
}
}

export type Magpie_provider_mimoPassed = {
  "code": number
  "userId": unknown
  "cUserId": string
  "passToken": string
  "location": string
  "desc": string
}

export type Magpie_provider_mimoSub = {
  "planCode": string
  "title": string
  "planTier": number
  "status": string
  "renewalMode": string
  "endTime": string
  "percent": number
  "nextResetTime": string
  "source": string
}

export type Magpie_provider_notStartedHook = Record<string, never>

export type Magpie_provider_planQuotaSource = Record<string, never>

export type Magpie_provider_PresetDef = {
  "id": string
  "name": string
  "icon": string
  "kind": Magpie_provider_Kind
  "chat"?: string
  "responses"?: string
  "anthropic"?: string
  "decide"?: string
  "catalog"?: string
  "website"?: string
  "keysUrl"?: string
  "noKey"?: boolean
  "sponsored"?: boolean
  "note"?: string
  "short"?: string
  "regions"?: (Array<Magpie_provider_Region>) | null
  "regionLabel"?: string
  "headerHints"?: (Array<string>) | null
  "only"?: string
  "models"?: (Array<string>) | null
  "noList"?: boolean
  "endpoint"?: string
  "endpointHint"?: string
}

export type Magpie_provider_promptFile = unknown

export type Magpie_provider_Protocol = string

export type Magpie_provider_Provider = {
  "id": string
  "name": string
  "was"?: (Array<string>) | null
  "icon"?: string
  "preset"?: string
  "key": string
  "keyName"?: string
  "keys"?: (Array<Magpie_provider_KeyAccount>) | null
  "keyProtocol"?: Magpie_provider_Protocol
  "chat"?: string
  "responses"?: string
  "anthropic"?: string
  "decide"?: string
  "fallback"?: (Array<string>) | null
  "routing"?: string
  "affinity"?: string
  "headers"?: (Record<string, string>) | null
  "proxy"?: string
  "accountProxies"?: (Record<string, string>) | null
  "balanceURL"?: string
  "balancePath"?: string
  "balanceToken"?: string
  "zhipuTeam"?: (Magpie_provider_ZhipuTeam) | null
  "modelsURL"?: string
  "models"?: (Array<string>) | null
  "unlisted"?: boolean
  "off"?: boolean
  "contexts"?: (Record<string, number>) | null
  "family"?: string
  "catalog"?: string
  "website"?: string
  "keysUrl"?: string
  "iconUrl"?: string
  "hidden"?: boolean
  "quiet"?: boolean
}

export type Magpie_provider_qoderFlow = Record<string, never>

export type Magpie_provider_Quota = {
  "provider": string
  "name": string
  "kind": string
  "plan"?: string
  "user"?: string
  "windows": (Array<Magpie_provider_QuotaSpan>) | null
  "balance"?: string
  "error"?: string
  "until"?: (string) | null
  "renew"?: string
  "resets"?: (Magpie_provider_ResetCredits) | null
}

export type Magpie_provider_QuotaSpan = {
  "name": string
  "used": number
  "remaining": number
  "resetsAt"?: (string) | null
  "display"?: string
}

export type Magpie_provider_QuotaWindow = {
  "name": string
  "used": number
  "resetsAt"?: (string) | null
  "resetSecs"?: number
  "display"?: string
}

export type Magpie_provider_quotaWire = {
  "utilization": number
  "resets_at": string
}

export type Magpie_provider_refreshRefused = string

export type Magpie_provider_Region = {
  "id": string
  "name": string
  "chat"?: string
  "responses"?: string
  "anthropic"?: string
  "lists"?: boolean
  "keysUrl"?: string
}

export type Magpie_provider_Renewal = {
  "agent": string
  "user": string
  "renewed": boolean
  "error"?: string
  "lapsed"?: boolean
}

export type Magpie_provider_ResetCredits = {
  "count": number
  "until"?: (string) | null
  "byWindow"?: boolean
  "fiveHour"?: number
  "weekly"?: number
}

export type Magpie_provider_ResetOutcome = {
  "code": string
  "windows": number
}

export type Magpie_provider_Result = {
  "protocol": Magpie_provider_Protocol
  "ok": boolean
  "status"?: number
  "ms": number
  "model"?: string
  "error"?: string
}

export type Magpie_provider_Rule = {
  "use": string
  "tokens"?: number
  "images"?: boolean
  "effort"?: string
  "agents"?: (Array<string>) | null
  "intent"?: string
  "compact"?: boolean
}

export type Magpie_provider_RuleRequest = {
  "Tokens": number
  "Images": boolean
  "Thinking": boolean
  "Effort": string
  "Agent": string
  "Intent": string
  "Compact": boolean
}

export type Magpie_provider_savedLogin = {
  "agent": string
  "user": string
  "plan"?: string
  "seen": string
  "on"?: boolean
  "auth": unknown
  "profile"?: unknown
  "home"?: string
  "first"?: boolean
  "project"?: string
  "renewed"?: string
  "lapsed"?: string
  "hidden"?: string
}

export type Magpie_provider_seenVersion = unknown

export type Magpie_provider_sideLogin = unknown

export type Magpie_provider_signInFlow = Record<string, never>

export type Magpie_provider_SignInState = {
  "id": string
  "agent": string
  "url": string
  "code"?: string
  "state": string
  "pasteCallback"?: boolean
  "installing"?: string
  "user"?: string
  "plan"?: string
  "using"?: boolean
  "error"?: string
}

export type Magpie_provider_stepfunClaims = {
  "activated": boolean
  "exp": number
  "oasis_id": unknown
}

export type Magpie_provider_stepfunSession = {
  "access": string
  "refresh": string
  "webId": string
  "account": string
}

export type Magpie_provider_SubscriptionQuota = {
  "provider": string
  "name": string
  "icon": string
  "plan"?: string
  "user"?: string
  "windows": (Array<Magpie_provider_QuotaWindow>) | null
  "balance"?: string
  "until"?: (string) | null
  "renew"?: string
  "error"?: string
  "asOf"?: (string) | null
  "resets"?: (Magpie_provider_ResetCredits) | null
}

export type Magpie_provider_warmState = (Record<string, (Record<string, Magpie_provider_warmWindow>) | null>) | null

export type Magpie_provider_warmWindow = {
  "resetsAt"?: string
  "used": number
  "warmed"?: string
  "pending"?: boolean
  "failed"?: number
  "daily"?: string
  "idle"?: number
  "retry"?: string
}

export type Magpie_provider_wbAccount = unknown

export type Magpie_provider_wbCheckinClaim = {
  "credit": Magpie_provider_wbNum
  "streak_days": Magpie_provider_wbNum
  "is_streak_day": boolean
  "credit_delayed": boolean
  "message": string
}

export type Magpie_provider_wbCheckiner = Record<string, never>

export type Magpie_provider_wbCheckinStatus = {
  "active": boolean
  "today_checked_in": boolean
  "streak_days": Magpie_provider_wbNum
  "daily_credit": Magpie_provider_wbNum
  "today_credit": Magpie_provider_wbNum
}

export type Magpie_provider_wbCreds = {
  "uid": string
  "accessToken": string
  "refreshToken": string
  "expiresAt": number
  "refreshExpiresAt": number
  "domain": string
  "tokenType"?: string
}

export type Magpie_provider_wbError = Record<string, never>

export type Magpie_provider_wbNum = number

export type Magpie_provider_wbProductConfig = {
  "agents": (Array<{
  "name": string
  "models": (Array<string>) | null
}>) | null
  "models": (Array<{
  "id": string
  "name": string
  "maxInputTokens": number
  "maxOutputTokens": number
  "supportsImages": (boolean) | null
  "onlyReasoning": boolean
  "credits": unknown
  "reasoning": {
  "supportedEfforts": (Array<string>) | null
  "canDisableThinking": (boolean) | null
}
}>) | null
}

export type Magpie_provider_wbRefreshed = {
  "accessToken": string
  "refreshToken": string
  "expiresAt": number
  "expiresIn": number
  "refreshExpiresAt": number
  "refreshExpiresIn": number
  "domain": string
  "tokenType": string
}

export type Magpie_provider_wbResourceSummary = {
  "Packages": (Array<{
  "PackageCode": string
  "CycleTotalCapacity": Magpie_provider_wbNum
  "CycleRemainCapacity": Magpie_provider_wbNum
  "CycleUsedCapacity": Magpie_provider_wbNum
}>) | null
  "SubscriptionPackageCode": string
  "IsPaidUser": boolean
}

export type Magpie_provider_wbSite = Record<string, never>

export type Magpie_provider_wbStoredSession = {
  "account": {
  "uid": string
  "nickname": unknown
  "phoneNumber": unknown
}
  "auth": {
  "accessToken": unknown
  "refreshToken": unknown
  "expiresAt": number
  "expiresIn": number
  "refreshExpiresAt": number
  "refreshExpiresIn": number
  "domain": string
  "tokenType": string
}
}

export type Magpie_provider_WorkBuddyCheckin = {
  "user"?: string
  "day": string
  "at": string
  "outcome": string
  "credit"?: number
  "streak"?: number
  "msg"?: string
}

export type Magpie_provider_zcodeBalance = {
  "server_time": unknown
  "plans": (Array<{
  "plan_id": string
  "user_plan_id": string
  "name": string
  "status": string
  "ends_at": unknown
  "entitlements": (Array<{
  "entitlement_id": string
  "period": string
}>) | null
}>) | null
  "balances": (Array<{
  "plan_id": string
  "user_plan_id": string
  "entitlement_id": string
  "show_name": string
  "capabilities": (Array<string>) | null
  "total_units": unknown
  "used_units": unknown
  "remaining_units": unknown
  "expires_at": unknown
  "period_start": unknown
  "period_end": unknown
}>) | null
}

export type Magpie_provider_zcodeBuiltin = {
  "revision": number
  "config": {
  "providerConfigRules": {
  "providerRules": (Array<{
  "providerId": string
  "builtinModelIds": (Array<string>) | null
}>) | null
}
  "modelConfigRules": {
  "modelRules": (Array<{
  "modelMatch": string
  "config": Magpie_provider_zcodeModelRule
}>) | null
  "builtinProviderModelRules": (Array<{
  "providerId": string
  "modelId": string
  "config": {
  "enabled": (boolean) | null
}
}>) | null
}
}
}

export type Magpie_provider_zcodeCustomer = {
  "organizations": (Array<{
  "organizationId": string
  "organizationName": string
  "projects": (Array<{
  "projectId": string
  "projectName": string
  "projectType": unknown
}>) | null
}>) | null
}

export type Magpie_provider_zcodeKey = {
  "apiKey"?: string
  "base": string
  "jwt"?: string
  "token"?: string
  "org"?: string
  "project"?: string
}

export type Magpie_provider_zcodeLoginKey = unknown

export type Magpie_provider_zcodeModelRule = {
  "properties": {
  "contextWindow": number
  "inputFormat": {
  "supportsImage": (boolean) | null
}
}
  "optionSpecs": {
  "maxOutputTokens": {
  "max": number
}
  "reasoningLevel": {
  "values": (Array<string>) | null
}
}
}

export type Magpie_provider_zcodeRoute = Record<string, never>

export type Magpie_provider_zcodeTeamDetail = {
  "hasSubscription": (boolean) | null
  "status": string
  "memberGrantStatus": string
  "productName": string
  "productId": unknown
  "subscribeEndTime": unknown
}

export type Magpie_provider_zcodeTeamKeyAt = Record<string, never>

export type Magpie_provider_zcodeTeamProject = Record<string, never>

export type Magpie_provider_zcodeTeamRefusal = string

export type Magpie_provider_zedCreds = {
  "userId": string
  "accessToken": string
  "systemId": string
  "organizationId"?: string
  "login"?: string
  "name"?: string
  "plan"?: string
  "models"?: unknown
}

export type Magpie_provider_zedLogin = unknown

export type Magpie_provider_zedTokenCache = Record<string, never>

export type Magpie_provider_zhipuLimits = {
  "limits": (Array<{
  "type": string
  "unit": number
  "number": number
  "usage": (number) | null
  "currentValue": (number) | null
  "remaining": (number) | null
  "percentage": (number) | null
  "nextResetTime": number
}>) | null
  "level": string
}

export type Magpie_provider_zhipuSubscription = {
  "status": string
  "valid": string
  "autoRenew": unknown
  "nextRenewTime": string
}

export type Magpie_provider_ZhipuTeam = {
  "org"?: string
  "project"?: string
}

export type Magpie_usage_Filter = {
  "Agent": string
  "Failed": boolean
  "Query": string
}

export type Magpie_usage_Group = unknown

export type Magpie_usage_Known = {
  "ID": string
  "Names": (Array<string>) | null
  "UA": (Array<string>) | null
}

export type Magpie_usage_Period = string

export type Magpie_usage_Point = unknown

export type Magpie_usage_Record = {
  "t": string
  "agent": string
  "provider": string
  "host"?: string
  "model": string
  "req"?: string
  "served"?: string
  "in": number
  "out": number
  "cache_read"?: number
  "cache_write"?: number
  "reasoning"?: number
  "effort"?: string
  "ms": number
  "ttft_ms"?: number
  "first_text_ms"?: number
  "status": number
  "session"?: string
  "kind"?: string
}

export type Magpie_usage_Row = unknown

export type Magpie_usage_Summary = unknown

export type Magpie_usage_Totals = {
  "calls": number
  "errors": number
  "input": number
  "output": number
  "cache_read": number
  "cache_write": number
  "reasoning": number
  "cost": number
  "unpriced": number
  "timed"?: number
  "ttft_ms"?: number
  "decode_ms"?: number
  "decode_out"?: number
}

export type Magpie_usage_Via = {
  "provider": string
  "model": string
  "effort"?: string
  "calls": number
  "tokens": number
  "last": string
}

